### ISSUE TITLE
Just a question. Delete after reply. Thanks.

### ISSUE THREAD

**Issue by vladpekh** [emailmonday/Cerberus#110]
Hi @TedGoas 

I missed a commit in which you've remove `<table>` between `<body>` and `<center>` tags.
Do you remember which commit was that or why this is a better approach?  

<img width="812" alt="screen shot 2017-03-23 at 5 44 57 pm" src="https://cloud.githubusercontent.com/assets/1377208/24271716/8cc81ade-0ff0-11e7-9606-b799cdaab65e.png">

Thank you in advance

**Comment by TedGoas** [comment]
I can't remember which commit. Could this be an artifact of [an archived version of Cerberus](https://github.com/TedGoas/Cerberus/tree/master/archived-versions/version%202)? 

I believe either approach works, `<center>` tag is just less code than a `<table>` tag and it's cells.
