### ISSUE TITLE
No inliner?

### ISSUE THREAD

**Issue by 9mm** [emailmonday/Cerberus#118]
I see this in the docs you're not supposed to inline the css... can you please explain a bit more on the implications of those?

Won't older email clients not show the email properly?

You mentioned something about 'snippets', I don't know what that is. Is this supposed to be an alternative to inlining it? If so can you explain what that is please?

**Comment by TedGoas** [comment]
I'm guessing you read [this](http://tedgoas.github.io/Cerberus/#css-inliners), it _should_ answer your question about older email clients.

> The placement of Cerberus’s CSS is already optimized. The CSS in the <head> is meant only for email clients that parse CSS in this location. It doesn’t need to be inlined.

[Here's what I mean by snippets](https://en.wikipedia.org/wiki/Snippet_(programming)). Litmus has [some handy ones just for email](https://litmus.com/community/snippets)!

**Comment by 9mm** [comment]
I know what a snippet is, but now I see what you mean. Thanks, that looks like a useful database!

About the other thing, I still don't quite understand the implications of not inlining CSS... perhaps because it's been ingrained so deeply that it feels crazy not to do it ("Everything will look terrible!!!"). Aren't there tons of old clients that won't show the email properly? Is it just that the usage of them is now < 0.5% or something and it's not worth maintaining them with this old style of writing CSS?

**Comment by TedGoas** [comment]
A lot of CSS is already inlined, albeit **by hand**. [Here's a random example](https://github.com/TedGoas/Cerberus/blob/master/cerberus-fluid.html#L202). This gives us the most control. Some CSS _should_ be inlined, and some _should not_. It's difficult for a CSS inliner to know the difference. The only one I know that does this is [Litmus Builder](https://litmus.com/email-builder).

Regarding CSS inlining, a lot of clients don't need it. Gmail was a long-time holdout, but they came around in fall of 2016. Even old Windows Outlook renders embedded CSS. [Here's an interesting post on the topic](https://litmus.com/community/discussions/6116-here-s-why-litmus-didn-t-inline-css-for-its-first-newsletter-of-2017).

**Comment by 9mm** [comment]
Ooooooh I see. Sorry, I didn't even view source code (yet). I really like this template though so I was gonna use it.

Thanks for explaining!
