### ISSUE TITLE
Thumbnail left and right h2, p, and button centering issue

### ISSUE THREAD

**Issue by designfrugal** [emailmonday/Cerberus#119]
I have noticed some other issue streams related to centering. This one seems particular to Nexus 5 and Outlook app on mobile devices. The thumbnail left and right h2, p, and button do not center. I have tried adjusting media queries for nexus and tried some class centering tricks for outlook, but have not found a consistent solution to deal with all main devices.

Below is a screenshot form EOA of nexus 5, outlook apps on mobile appear the same.
![sc_thumbnail_nexus5](https://user-images.githubusercontent.com/15806717/28149491-f83d94a2-675b-11e7-8af6-fc385e27fc00.png)

**Comment by TedGoas** [comment]
@designfrugal Outlook app and (I'm guessing) the version of Android on this Nexus **don't support media queries**, so I'm afraid this is the best we can do without centering the text on desktop as well. These clients relying on hybrid coding to stack the columns, but that's about the only adjustment they can do on mobile.

**Comment by designfrugal** [comment]
The use case from a recipient perspective is pretty low, but from a internal review process, the majority of stakeholders view test emails via outlook on their mobile device, at least where I am at. This is something I will look into more and keep an eye on, and fingers crossed, outlook app will play nice someday. :)  Thanks for responding.

**Comment by TedGoas** [comment]
@designfrugal Outlook app _actually has_ gone back and forth between media query support! When it launched, it didn't have it. Then later, it added it in. But then an update last year removed it. No idea what's going on, but worth keeping an eye on for sure!
