### ISSUE TITLE
CSS file?

### ISSUE THREAD

**Issue by simondoescode** [emailmonday/Cerberus#121]
Is there a CSS file with all of the styles? 

I'm using Node and Gulp to inline the css into the HTML.

**Comment by TedGoas** [comment]
@SimonFricker No, there is no CSS file. All the styles are in the document `<head>` or are already inlined. I recommend _against_ using an inliner; [more on that here](http://tedgoas.github.io/Cerberus/#css-inliners). Of course, you're free to use one if you'd like.

**Comment by simondoescode** [comment]
ok thank you.
