### ISSUE TITLE
Update VML backgrounds to improve Windows 10 and Outlook DPI

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#122]
Try something like this:

    <! — [if gte mso 9]>
          <v:image xmlns:v=”urn:schemas-microsoft-com:vml” id=”theImage” style=”behavior: url(#default#VML); display: inline-block; width:525pt; height:348.75pt; top: 0; left: 0; border: 0; z-index: 1;” src=”image.jpg" /> 
          <v:rect xmlns:v=”urn:schemas-microsoft-com:vml” fill=”true” stroke=”false” style=”display: inline-block; position: relative; width:525pt; height: 161.25pt; top: 187.5pt; left: 0; border: 0; z-index: 2;”>
          <v:fill opacity=”0%” style=”z-index: 1;”/> 
     <![endif] ->

---
[source](https://medium.com/@ka.robinson82/https-medium-com-ka-robinson82-fargo-email-6907f00fed16)

**Comment by dyspop** [comment]
doesn't work?

**Comment by TedGoas** [comment]
@dyspop can you explain?
