### ISSUE TITLE
Re: cerberus-hybrid.html

### ISSUE THREAD

**Issue by syfer-darknight** [emailmonday/Cerberus#127]
Hi Ted,

On the cerberus-hybrid.html (master), there seems to be two classes on the hero banner. Its breaking the image in Dreamweaver design view.

Multiple classes:
![image](https://user-images.githubusercontent.com/3690403/29438796-7ef2a052-83fc-11e7-90d0-bc4f51d339da.png)

View in Dreamweaver
![image](https://user-images.githubusercontent.com/3690403/29438804-8bcaecc6-83fc-11e7-902a-8a0d79cc53a8.png)

Cheers

**Comment by vladpekh** [comment]
@syfer-darknight I would honestly never trust Dreamweaver design view. It's just not accurate. Do you have same issue in Litmus?

**Comment by TedGoas** [comment]
@syfer-darknight g'ahh what a stupid mistake, thanks for pointing out! I'll fix and check the others.

@volodymyrpekh Generally I wouldn't either, but in this case it pointed out an obvious mistake on my part!

**Comment by syfer-darknight** [comment]
@volodymyrpekh 
I have been told not to trust dreamweaver for many years but i dont see anything wrong with it so far. The reason I pointed this out was there will be many users that use dreamweaver and would see the break in template. 

@TedGoas 
Personally i think Cerberus looks really good. No rendering issues or anything of that sort. 👍 

Just know am not picking a fight or pointing fingers, just wanted to see a full working template :-)
