### ISSUE TITLE
"View A Demo" links not working

### ISSUE THREAD

**Issue by drewtunney** [emailmonday/Cerberus#128]
The `View A Demo` button for the templates link all return a page that says `No definition found for Table headers`

![screen shot 2017-08-24 at 1 35 43 pm](https://user-images.githubusercontent.com/4064746/29679981-2da46c88-88d1-11e7-8270-deeab56794c8.png)

**Comment by TedGoas** [comment]
@drewtunney Is this working now on your end? I use [http://htmlpreview.github.io/](http://htmlpreview.github.io/) for this, I wonder if the service was down earlier.

**Comment by drewtunney** [comment]
@TedGoas yep, it's working. I think you're right. There was no change in the code when it stopped working. Thanks for the templates!

**Comment by drewtunney** [comment]
@TedGoas just a heads up that this is a recurring issue. The same errors happened yesterday and today

**Comment by TedGoas** [comment]
@drewtunney I've noticed this too. Usually refreshing the page once or twice fixes it. I'll keep an eye on it and also for alternatives (have any?).

**Comment by drewtunney** [comment]
@TedGoas ok thanks, good to know. Unfortunately I do not off the top of my head, sorry. I will keep an eye out.
