### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by ananthb** [emailmonday/Cerberus#133]

**Comment by ananthb** [comment]
Bower has been deprecated for some time now. A package.json might make sense.

**Comment by TedGoas** [comment]
@ananthb I had no idea, thanks for pointing out! How does [this one](https://github.com/TedGoas/Cerberus/blob/master/package.json) look?

**Comment by ananthb** [comment]
That looks great. Thanks.

Are you publishing this package on npm as well?

**Comment by TedGoas** [comment]
@ananthb I hadn't really thought about it. What are the advantages of publishing something on npm?
