### ISSUE TITLE
Question re email-container class

### ISSUE THREAD

**Issue by nickpish** [emailmonday/Cerberus#134]
Hi, I just have a basic question on when to use the `email-container` class when creating an email based on your `cerberus-responsive.html` template. In the template file, the class seems to be applied to all the outermost tables acting as containers, i.e. header, body and footer, yet it's also applied to a `div` nested within a table in the "full bleed background section." In the case that I wanted to nest one table inside another to provide uniform padding around multiple elements within the email body—as in the example below—would I only need to apply the `email-container` class to the outermost table? Thank you for any feedback here.

Example:
```
<!-- CONTAINER -->
<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" class="email-container">
   <tr>
      <td valign="top" align="center" style="padding:20px">
         <!-- BODY CONTENT -->
         <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%">
            <tr>
               <td valign="top" align="center">{BODY CONTENT HERE}</td>
            </tr>
            <tr>
               <td valign="top" align="center">{MORE BODY CONTENT HERE}</td>
            </tr>
         </table>
      </td>
   </tr>
</table>
```

**Comment by TedGoas** [comment]
> would I only need to apply the email-container class to the outermost table?

@nickpish The `.email-container` class should be applied to the portion(s) of your email that constrain the email width on wide layouts (eg. doesn't exceed 600px on desktop) but become flexible on narrow layouts (eg. email is 100% on whatever mobile device). It's not _always_ the outermost table, as in the case with the "full bleed background section" in Cerberus.

Does that make sense?

Generally `.email-container` controls the email width and any responsible fluidity. I'd recommend doing any padding in a nesting table inside `.email-container`.

**Comment by nickpish** [comment]
@TedGoas that makes sense, thanks—and as far as nesting a table inside `.email-container` for padding, as you mentioned, my example above with the padding added to the `td` of the `.email-container` should work fine, no? Or should I actually nest an additional table within `.email-container` and apply the padding to the `td` associated with *that* table? Thanks for the clarification.

**Comment by TedGoas** [comment]
@nickpish Yea the way you have it above should work!

**Comment by nickpish** [comment]
@TedGoas Great, thanks!
