### ISSUE TITLE
Pictures only partially displayed in Win10 Outlook 2016

### ISSUE THREAD

**Issue by ghost** [emailmonday/Cerberus#135]
In Desktop Outlook 2016 most images in the template (in my case the responsive template) are only partially displayed after downloading them. Always some of the upper part is not displayed. If I click on it then it shows the correct shape of the image but only the lower part is displayed:

![grafik](https://user-images.githubusercontent.com/20925669/31828970-2caf7738-b5bc-11e7-9a3d-d6f780425540.png)

In Outlook online, it works like a charm and also on any other tested mail client like google etc.

Does anyone else has this issue?

**Comment by TedGoas** [comment]
@webkaktus My gut tells me it's something with `line-height`. Can you reproduce this using Cerberus's default code? I'm not sure how to reproduce your code above.

**Comment by webkaktus** [comment]
Yes I also think so. I tested it with the default template (fluid-template) and just added this code:

```
<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px; text-align: left;">
	<tr>
		<td style="text-align: center;font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0;" class="stack-column-center">
			<a href="https://google.com"><img src="https://linktoimage.jpg" width="32" height="32" style="padding-right: 5px;"></a>
			<a href="https://google.com class="facebook"><img src="https://linktoimage.jpg" width="32" height="32" style="padding-right: 5px;"></a>
			<a href="https://google.com" class="instagram"><img src="https://linktoimage.jpg" width="32" height="32" style="padding-right: 5px;"></a>
			<a href="https://google.com" class="youtube"><img src="https://linktoimage.jpg" width="32" height="32"></a>
		</td>
	</tr>
</table>
```

Still the same:
![grafik](https://user-images.githubusercontent.com/20925669/31834875-c7a21832-b5cf-11e7-85b5-ae4ef641897f.png)

**Comment by ghost** [comment]
You're right it was indeed a problem with the `line-height`-property. I had to adjust/remove it on different places and now it works.

Sorry for opening an issue for that and thanks for your quick response!
Webkaktus

**Comment by TedGoas** [comment]
@webkaktus nice, glad you got it sorted out. Cheers!
