### ISSUE TITLE
gmail issue

### ISSUE THREAD

**Issue by metalgigio** [emailmonday/Cerberus#140]
Hi,
as you can see the cerberus-hybrid.html does not display properly on gmail on android.

![screenshot_20171115-121149](https://user-images.githubusercontent.com/785743/32833184-5100742e-c9fe-11e7-9329-3ff22011baa7.png)

**Comment by metalgigio** [comment]
It's a strange bug. If i remove Email Header table o Hero Image row it display correctly, but not if i have both...

**Comment by metalgigio** [comment]
after some test i found that the problem is here:

```
        /* What it does: Forces Gmail app to display email full width */
        u ~ div .email-container {
	        min-width: 100vw;
        }
```

just remove that to make it display correct.
Does remove it affects visualizzation on other clients?

**Comment by n00bium** [comment]
Hey there, 
i am having the same Problem but I could not reproduce @metalgigio´s suggestion. It is also worth mentionign that the hybrid-template is also broken on Gmail-Webview .
![gmail-web](https://user-images.githubusercontent.com/33716941/32883833-c427f444-cab8-11e7-9e09-f8492d4526fe.png)

**Comment by n00bium** [comment]
```
 /* What it does: Forces Gmail app to display email full width */
        u ~ div .email-container {
	        min-width: 100vw;
        }
```
Removing this does the Trick on Mobile and Web! Great find @metalgigio !

**Comment by TedGoas** [comment]
@metalgigio @n00bium I'm having trouble reproducing your issue. This is what I see in Litmus:

![screen shot 2017-11-16 at 9 57 30 am](https://user-images.githubusercontent.com/1172461/32897916-c8a99c2e-cab4-11e7-9c34-a2e9d6e3790f.png)

---

![screen shot 2017-11-16 at 9 57 37 am](https://user-images.githubusercontent.com/1172461/32897926-cd353f14-cab4-11e7-9079-73a011fb187f.png)

**Comment by metalgigio** [comment]
I tested on a nexus 5 and a galaxy s7, both with last version of gmail app. Maybe on litmus they don't have last version of gmail...

**Comment by n00bium** [comment]
I tested on a Oneplus One and on Firefox 56 running on Windows 10.  So there is probably something fishy over at litmus´.

**Comment by TedGoas** [comment]
@metalgigio @n00bium FYI removing this will break Gmail on iOS.

    /* What it does: Forces Gmail app to display email full width */
        u ~ div .email-container {
	        min-width: 100vw;
        }

This code is supposed to target only one OS. Looking into updating it so it doesn't bleed into where it shouldn't.

**Comment by metalgigio** [comment]
@TedGoas what do you mean for break? i do not have ios device to test it

**Comment by TedGoas** [comment]
@metalgigio this: https://github.com/TedGoas/Cerberus/issues/137

**Comment by metalgigio** [comment]
Thanks. i think that until we will find a solution i will remove that lines of code, it's seem that bugs on android is worst than on ios (on android it's let u scroll on right like it was bigger that container)

**Comment by TedGoas** [comment]
Sounds good. I'll leave this open and work on this so hopefully we can get both Gmail's acting consistently.

**Comment by TedGoas** [comment]
[Note to self](http://freshinbox.com/blog/targeting-new-gmail-css/)

**Comment by ghost** [comment]
Just to add to this that I had the same issue, removing those lines has fixed it for me on Gmail desktop (viewing on Chrome Linux) and mobile (Huawei P9 Gmail App).

**Comment by SilverHazeLazers** [comment]
I have taken a shot at resolving this issue using the link Ted provided. Pull request here #146 

Tested as working on latest version of gmail app.
