### ISSUE TITLE
[Proposal] Gallery or slideshow template

### ISSUE THREAD

**Issue by Modelizer** [emailmonday/Cerberus#142]
Can we get gallery or slideshow template in Cerberus? As per [Rebelmail Gallery Template](https://docs.rebelmail.com/docs/gallery) it is possible and there are few resources which claims that they did it. But I'm certain here to know the limitations and fallback.

Curies to see in Cerebrus. Thanks for the great work! 👍

**Comment by tomablan** [comment]
Hey !

Has someone has an idea / url for the client compatibility of this ? If a medium range of client are ok (like the ones that support current responsive behaviour), maybe not Ted, but the community here can help ? Pull requests are opened :)

**Comment by TedGoas** [comment]
Sorry gents, gonna pass on this one.

Cerberus is "A few simple, but solid patterns" for email, that's [what's on the tin](http://tedgoas.github.io/Cerberus/). Interactive is anything but simple and solid. There are multiple levels of support and fallbacks required to cover all major email clients. ESP's have their own rules about what they allow and what they _change_ when importing code. Not something I really want to support.

Add to the my inexperience in building them. I'm not the right person to develop, maintain, troubleshoot, and evolve a pattern like this. I usually turn to folks like [Mark Robbins](https://twitter.com/M_J_Robbins) (Rebel) and [Justin Khoo](https://twitter.com/FreshInbox). [Here's one of Justin's examples](https://www.emailonacid.com/blog/article/email-development/build-an-interactive-carousel-for-email) if you'd like something to start from.
