### ISSUE TITLE
Install with NPM

### ISSUE THREAD

**Issue by alegout** [emailmonday/Cerberus#143]
Hello,

Thanks for Cerberus!
Trying to install it with npm:

npm install TedGoas/Cerberus.git#3.0.0 --save

But not working, is there an another way to install it via NPM?

Thank you!

**Comment by TedGoas** [comment]
`¯\_(ツ)_/¯` No idea, I'm not familiar with using `npm` to install things. I only added a package file because [someone asked](https://github.com/TedGoas/Cerberus/issues/133).

Part of me wonders if `npm` is overkill in this case. Cerberus **is only three HTML files**, so you download them as needed.

**Comment by alegout** [comment]
Do not think so, was on bower before and trying to switch to npm like the related issue you mentioned.

I tried again this evening, but no results.

**Comment by TedGoas** [comment]
Sorry, I really don't know anything about `npm`. If the `npm` package doesn't work, maybe it should be removed.

**Comment by alegout** [comment]
The package.json looks good to me, maybe it’s my configuration, i will try to install Cerberus outside my project, tell you more in a few hours. Thank you for your help!

**Comment by dyspop** [comment]
I had the same issue trying to install with npm. 

```
84 error Darwin 16.7.0
85 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "TedGoas/Cerberus.git#3.0.0" "--save"
86 error node v6.11.5
87 error npm  v3.10.10
88 error code EISDIR
89 error errno -21
90 error syscall read
91 error eisdir EISDIR: illegal operation on a directory, read
92 error eisdir This is most likely not a problem with npm itself
92 error eisdir and is related to npm not being able to find a package.json in
92 error eisdir a package you are trying to install.
93 verbose exit [ -21, true ]
```

**Comment by dyspop** [comment]
without save it's easier to read:

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "TedGoas/Cerberus.git#3.0.0"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read
```

**Comment by TedGoas** [comment]
> This is most likely not a problem with npm itself and is related to npm not being able to find a package.json in a package you are trying to install.

@dyspop ???

**Comment by dyspop** [comment]
@TedGoas this is the error output from when I tried to install it. I do see that you have a a package.json file, but for whatever reason the file can't be read.

**Comment by dyspop** [comment]
I made sure my npm was up-to-date and reran. I got a slightly different error description:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'TedGoas/Cerberus.git#3.0.0' ]
2 info using npm@5.6.0
3 info using node@v6.11.5
4 verbose config Skipping project config: /Users/dblack/.npmrc. (matches userconfig)
5 verbose npm-session b8c1c808045f4e39
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for github:TedGoas/Cerberus#3.0.0 ENOENT: no such file or directory, open '/Users/dblack/.npm/_cacache/tmp/git-clone-94875d3c/package.json'
9 verbose stack Error: ENOENT: no such file or directory, open '/Users/dblack/.npm/_cacache/tmp/git-clone-94875d3c/package.json'
9 verbose stack     at Error (native)
10 verbose cwd /Users/dblack
11 verbose Darwin 16.7.0
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "TedGoas/Cerberus.git#3.0.0"
13 verbose node v6.11.5
14 verbose npm  v5.6.0
15 error path /Users/dblack/.npm/_cacache/tmp/git-clone-94875d3c/package.json
16 error code ENOENT
17 error errno -2
18 error syscall open
19 error enoent ENOENT: no such file or directory, open '/Users/dblack/.npm/_cacache/tmp/git-clone-94875d3c/package.json'
20 error enoent This is related to npm not being able to find a file.
21 verbose exit [ -2, true ]
```

**Comment by TedGoas** [comment]
@dyspop I don't know much about `npm`. Anything seem wrong with the [`package.json` file](https://github.com/TedGoas/Cerberus/blob/master/package.json)? Any idea what is causing this?

**Comment by alegout** [comment]
Example:

`npm install https://github.com/TedGoas/Cerberus/tarball/master`

should work, but get:

`npm ERR! Invalid version: "3.0"`

Cause of the semver package. Should be "3.0.0". 
see https://github.com/npm/npm/issues/7445

Maybe if setting version to 3.0.0 in package.json it'll work. 
The other problem (maybe?), is your last release does not have the package.json inside.

Hope it helps!

**Comment by TedGoas** [comment]
@alegout ^^ updated the version to `3.0.0`, any luck?

**Comment by alegout** [comment]
All good!

```
root@b43d80d49a6b:/var/www/# npm install github:TedGoas/Cerberus --save
+ Cerberus@3.0.0
added 1 package in 5.819s
```

Thank you very much for your help and your work @TedGoas 

The only problem left, if you have some time, it's we cannot install a chosen version of Cerberus like:

`npm install github:TedGoas/Cerberus#3.0.0 --save`

Because the actual 3.0.0 does not have the package.json, error:

```
root@b43d80d49a6b:/var/www/# npm install github:TedGoas/Cerberus#3.0.0 --save
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:TedGoas/Cerberus#3.0.0.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

**Comment by TedGoas** [comment]
@alegout I don't know what most of that means... what should I do to fix it?

**Comment by alegout** [comment]
I think you should create a new release in https://github.com/TedGoas/Cerberus/releases, like a 3.0.1 (i'm not good for semantic versioning, https://semver.org/) and package.json will be in.
It should work after cause npm will find it if we:

npm install github:TedGoas/Cerberus#3.0.1 --save

Thank you 👍

**Comment by TedGoas** [comment]
@alegout why would you want to download anything but the latest release?

**Comment by alegout** [comment]
It's a common practice to set a version, not the latest to avoid issues.

**Comment by dyspop** [comment]
because node development moves too fast

**Comment by TedGoas** [comment]
@alegout @dyspop Would that mean I'd have to update the package file's "3.0.**this number**" each time an update is pushed? I still don't understand the use case here.

**Comment by alegout** [comment]
Imagine my app use Cerberus 3.0.0, all work fine, but i always get the latest release when i npm update. 
If i do not set a fixed release version for Cerberus, maybe in version 4, my app will not work anymore with Cerberus (for X reasons). 
But if i can force my app to always use the 3.0.0 version i won't have this problem because i know it's working fine with the 3.0.0.

**Comment by TedGoas** [comment]
K I think I understand how this works and why some folks would find it useful. Going forward I'll try to create patch releases and update the package file from time to time. Fair warning: I don't plan on adopting this sort of workflow myself, so I probably won't put _too_ much effort into this.

Thanks for being patient with me :)

**Comment by alegout** [comment]
I totally understand, and a version from time to time is perfect :)
Thank you again for all your work.

And... Merry christmas!!! 🎄 🎅 ☃️
