### ISSUE TITLE
retina iphone 6

### ISSUE THREAD

**Issue by allbizznet** [emailmonday/Cerberus#144]
Hi All
I have a problem with iphone 6 with 2 or 3 columns.
In portrait mode this should show 1 column and in landscape mode 3 columns .
With retina phones, it always display 3 columns.

Can someone help me in order to have 1 column in portrait mode ?
thanks

**Comment by TedGoas** [comment]
@allbizznet Changing [the width where the media query takes effect](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L138) allows you to stack or unstack the columns at whatever width you'd like.

**Comment by allbizznet** [comment]
Thanks for you reply. In fact it was a problem with the client "orange mailer" app. If I copy in html, with safari, it's works fine.
There are so much tools. Emailing is very difficult to work everywhere.

**Comment by TedGoas** [comment]
@allbizznet Cool, glad you found the root cause. Yes, emailing is difficult even with tools :)
