### ISSUE TITLE
(Current) Windows 10 Mail App ignores CSS?

### ISSUE THREAD

**Issue by Spegeli** [emailmonday/Cerberus#149]
Your Template works perfect but today i found out that the Windows 10 Mail App seems to ignore the CSS!?

Here is a Screenshot which showes the responsive once: http://i.epvpimg.com/Vdjsfab.png

As you see the Background Color is missing, the Button has no rounded corners aso.

Any solution?

**Comment by Spegeli** [comment]
Found a Solution for the Background:
```
<body width="100%" bgcolor="#222222" style="margin: 0; mso-line-height-rule: exactly;">
    <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" align="center" style="width:100%;" bgcolor="#222222">
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
    <![endif]-->
...
    <!--[if mso | IE]>
		</td></tr></table>
   <![endif]-->
```

but the rest of the css is stil not working ;-(

**Comment by TedGoas** [comment]
@Spegeli Windows 10 Mail has _very_ limited CSS supported, even worse [than Outlook](https://www.campaignmonitor.com/css/email-client/outlook-2007-16/). Things like rounded corners are not possible in Windows 10 Mail 😞

---

The background issue _might_ be resolved by using the solution you posted. Also [found here](https://github.com/mjmlio/mjml/issues/572). You've tested this with success?

**Comment by Spegeli** [comment]
@TedGoas yeah right found the background solution on the same page. tested and works.

thx for the info that css is limited on windows 10 mail.

padding and margin also not supported by Windows 10 Mail?

**Comment by TedGoas** [comment]
@Spegeli `padding` should be reliable, but not so much `margin`.

**Comment by TedGoas** [comment]
@Spegeli Just pushed a commit that should resolve this. I modified your code suggestion above to cover all email clients. We need `<center>` to cover a handful of webmail clients, but can remove the `bgcolor` attribute from `<body>` (one less thing to manage). Thanks again for your help finding this and pointing towards a fix!

Here's what I committed:

```
<body width="100%" style="margin: 0; mso-line-height-rule: exactly;">
    <center style="width: 100%; background: #222222; text-align: left;">
    <!--[if mso | IE]>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#222222">
    <tr>
    <td>
    <![endif]-->
```

**Comment by vishalims095** [comment]
windows mail app : ![emailissue1](https://user-images.githubusercontent.com/36037597/137076635-5dde59cc-252a-41ce-beea-81e7e13c0e5c.png)

normal mail : ![email2](https://user-images.githubusercontent.com/36037597/137076696-95d899b2-21ce-4318-a410-a82cf4e33d58.png)

email template not working

**Comment by TedGoas** [comment]
Hi, can you re-produce this using the original code in this repo (rather than code you've edited)?
