### ISSUE TITLE
Buttons on Airmail iOS

### ISSUE THREAD

**Issue by ronnieduke** [emailmonday/Cerberus#152]
For some reason the button does not display correctly on Airmail for iOS:

![image](https://user-images.githubusercontent.com/742579/36167156-bc03446c-10a9-11e8-908b-6c987fa484c3.png)

I did find that adding the background color and !important to the `<span>` ended up fixing it:

```
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#ffffff;background: #E44A35 !important">Read More</span>&nbsp;&nbsp;&nbsp;&nbsp;
```

The button now displays correctly in Airmail:
![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/742579/36167281-28b75de6-10aa-11e8-95af-8b95a926e787.png)

**Comment by TedGoas** [comment]
@ronnieduke Hmm, that's odd.

`<span style="color:#ffffff; background: #E44A35 !important">`

Curious, does removing this `!important` still fix it? I don't have a copy of Airmail to test this myself.

**Comment by TedGoas** [comment]
@ronnieduke Howdy, I just committed [an update](https://github.com/TedGoas/Cerberus/issues/180) around button styles and colors. I don't suppose you'd be able to pull a fresh copy of one of the templates and test it in your copy of Airmail? Fingers crossed 🤞

**Comment by TedGoas** [comment]
@ronnieduke Hello, just taking the temperature here. Have you tested this recently in Airmail? How much appetite do we have to dig into this?

**Comment by TedGoas** [comment]
Gonna close for now, but feel free to reopen if this is still a problem. ✌️
