### ISSUE TITLE
Image STRETCH !!!!!!!!!!

### ISSUE THREAD

**Issue by putuoka** [emailmonday/Cerberus#154]
when i tried to change the image size it's stretch and this is not good please take a look
https://i.imgur.com/wfp7kgo.png

**Comment by TedGoas** [comment]
@putuoka I'm not sure what' you're trying to do based on your screenshot. If you'd like to make the images _smaller_, you can adjust the `width` attribute and inline CSS `width`. The images will always keep their aspect ratio and will not exceed the width of their container.

**Comment by putuoka** [comment]
i want to change default 200x200 image box into 210x241, 208x241, and 209x241 like in the picture above. let say for example i have different image size than your default template. which one should i change to make it not stretch ?

edit: nvm thanks i got it. i need to change and hardcoded width, max-width, and height

**Comment by TedGoas** [comment]
Without changing the width of the email, the maximum width these images will go is 200px. So if they are all _more_ than 200px, they'll all be scaled down to the same width. 

As you mentioned, you need to update the hard-coded `width` and `max-width`. I would recommend _against_ adding a `height` since that will cause the image to become unresponsive.

**Comment by TedGoas** [comment]
> nvm thanks i got it. i need to change and hardcoded width, max-width, and height

Assuming this is safe to close. Feel free to comment further.

**Comment by putuoka** [comment]
> I would recommend against adding a height

i think if you not define width and height it will goes messy in outlook 2007

**Comment by TedGoas** [comment]
> i think if you not define width and height it will goes messy in outlook 2007

All versions of Outlook will scale these images as defined and keep their aspect ratio!
