### ISSUE TITLE
Include the &zwnj;&nbsp; Preview Text Hack?

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#156]
Cerberus already has preview text, why not add the `&zwnj;&nbsp;` to enhance it a bit? [Jaina Mistry explains it @ Litmus Live](https://www.youtube.com/watch?v=d5lwydFLnd4)

**Comment by dyspopresponsysrest** [comment]
super agree! is there any recommended "max" length? i use quite a large block of them.

**Comment by TedGoas** [comment]
@dyspopresponsysrest I've heard something [around 490 characters](https://github.com/TedGoas/Cerberus/blob/master/cerberus-fluid.html#L179), but that was a while ago. Larger phones (iPhone X) have been released since then, so they might show more.
