### ISSUE TITLE
Cerberus Hybrid Background color changes to default in Outlook 2013

### ISSUE THREAD

**Issue by putuoka** [emailmonday/Cerberus#159]
i try to change background color of the page to #d4d4d4 from default color #222222
![image](https://user-images.githubusercontent.com/20880839/37635299-beba52ca-2c35-11e8-9fdd-4169f667fc58.png)

it should be show like this in any email platform. Gmail web show it correctly but outlook 2013 failed.
![image](https://user-images.githubusercontent.com/20880839/37635180-27683e82-2c35-11e8-81bf-e890a39a99c7.png)

in outlook 2013 it changes automatically back to original template color which is #222222
![image](https://user-images.githubusercontent.com/20880839/37635223-69f956f0-2c35-11e8-9328-cb7431e21bec.png)

i'm using campaign monitor to send the email
my outlook version is 2013

**Comment by TedGoas** [comment]
The background color appears in multiple times in the code to cover all email clients, so you need to update the color in all locations.

<img width="477" alt="screen shot 2018-03-20 at 8 11 34 am" src="https://user-images.githubusercontent.com/1172461/37653804-7e191f54-2c16-11e8-8aea-4e2f76bd4e19.png">

---

I'll leave this bug open to remind myself to write better documentation around this!

**Comment by putuoka** [comment]
@TedGoas haha sorry my bad. Thank you so much for the great work. i'll be careful next time this is because user case me to convert old edm and landing page in short time. i write in rush can't read n check whole html even after ctrl+f #222222 i still blind :p
