### ISSUE TITLE
Question about Email Footer section

### ISSUE THREAD

**Issue by meowsus** [emailmonday/Cerberus#162]
It seems to me that there is a lot of cruft [in this section](https://github.com/TedGoas/Cerberus/blob/master/cerberus-fluid.html#L323) of the templates.

I'm curious if there was a reason why this section

```html
<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px; font-family: sans-serif; color: #888888; font-size: 12px; line-height: 140%;">
    <tr>
        <td style="padding: 40px 10px; width: 100%; font-family: sans-serif; font-size: 12px; line-height: 140%; text-align: center; color: #888888;" class="x-gmail-data-detectors">
            <webversion style="color: #cccccc; text-decoration: underline; font-weight: bold;">View as a Web Page</webversion>
            <br><br>
            Company Name<br>123 Fake Street, SpringField, OR, 97477 US<br>(123) 456-7890
            <br><br>
            <unsubscribe style="color: #888888; text-decoration: underline;">unsubscribe</unsubscribe>
        </td>
    </tr>
</table>
```

isn't structured more like the other sections:

```html
<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
    <tr>
        <td class="x-gmail-data-detectors" style="padding: 40px 10px;">
            <p style="font-family: sans-serif; font-size: 12px; line-height: 140%; text-align: center; color: #888888;">
                <webversion style="color: #cccccc; text-decoration: underline; font-weight: bold;">View as a Web Page</webversion>
                <br><br>
                Company Name<br>123 Fake Street, SpringField, OR, 97477 US<br>(123) 456-7890
                <br><br>
                <unsubscribe style="color: #888888; text-decoration: underline;">unsubscribe</unsubscribe>
            </p>
        </td>
    </tr>
</table>
```

I implemented the hybrid version recently and used something closer to this second code snippet in our project. It seemed to work well.

My question is is this extra code a relic that should be removed, or does it serve some eldritch purpose?

If it's the latter, I'd be happy to fire off a PR for you.

Thanks for your time.

**Comment by TedGoas** [comment]
Hmm, no reason. I don't see a _huge_ difference between the two examples... the latter includes the text inside a `<p>` with inline text styles. What is the 'extra code' and 'cruft' you're referring to?

**Comment by meowsus** [comment]
Specifically the duplication on `table` and `td` styles. These are shared by both:

```
font-family: sans-serif; color: #888888; font-size: 12px; line-height: 140%;
```

And on the `td`, this style seems superfluous: 

```
width: 100%;
```

Looking again at the sections more closely, this change should simply bring it in line with the others

```
<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
    <tr>
        <td class="x-gmail-data-detectors" style="padding: 40px 10px; text-align: center; font-family: sans-serif; color: #888888; font-size: 12px; line-height: 140%;">
            <webversion style="color: #cccccc; text-decoration: underline; font-weight: bold;">View as a Web Page</webversion>
            <br><br>
            Company Name<br>123 Fake Street, SpringField, OR, 97477 US<br>(123) 456-7890
            <br><br>
            <unsubscribe style="color: #888888; text-decoration: underline;">unsubscribe</unsubscribe>
        </td>
    </tr>
</table>
```

The only reason I'm bringing this up is because email formatting is a huge mystery to a lot of people. When I got down to this last section I felt the need to keep this code duplicated in both spots, but since there was no explanation I had no idea why that might be necessary.

Also, in the above snippet, I've changed the `680px` to `600px` to match the others, since this seemed like an error as well.

**Comment by meowsus** [comment]
Gladly
