### ISSUE TITLE
i found out does not working with inbox25 (inbox25.com)

### ISSUE THREAD

**Issue by putuoka** [emailmonday/Cerberus#164]
I have done converting my old EDM into cerberus hybrid template
its working quite fine in outlook 2013 and gmail web desktop but..
it's show very messy when open with gmail app for android.

i don't know how to check but i have feeling if [mso] isn't supported by inbox25

**Comment by TedGoas** [comment]
What is inbox25.com? Looks like an email service provider (ESP), is that true?

If so, what exactly is the problem? You've created an email, sent it through inbox25.com, and it looks messed up when you open it in Gmail app for Android.

**Comment by TedGoas** [comment]
@putuoka Ping! Just wanted to make sure you saw my question above.

**Comment by putuoka** [comment]
@TedGoas sorry sir for late reply. I don't know how to check so i decide to come with other solution by modified my old EDM to use some of your project function like add your image implementation auto height and iphone meta. So in conclusion your project doesn't meet to my company because we use inbox25 and inbox25 is rubbish i think lol. i close this issues. 

Thank you so much.
