### ISSUE TITLE
Mailchimp Preview Scroll

### ISSUE THREAD

**Issue by superpowered** [emailmonday/Cerberus#165]
This is possibly a non issue, as it likely doesn't translate to actual Email Clients, but thought I'd put it out on the radar since there's probably other people here who use MailChimp.

But if you take the Hybrid Template and put it into MailChimp and try to preview the email on mobile, there's about a 20px scroll to the right.

It's specifically caused by the iPhone 6-8 media query target:
```
 /* iPhone 6+, 7+, and 8+ */
        @media only screen and (min-device-width: 414px) {
            .email-container {
                min-width: 414px !important;
            }
        }

```

![screen shot 2018-04-18 at 5 10 50 pm](https://user-images.githubusercontent.com/7035467/38961094-8fbeef40-432c-11e8-8888-67bb3b513680.png)

**Comment by TedGoas** [comment]
@superpowered Huh, that's weird. How does it display when you send a test email from MailChimp and open it on an actual iPhone? Something you can test?

**Comment by superpowered** [comment]
@TedGoas Sending the test email it looked fine on my iPhone 6. I don't have a 6+ or later to test on, however.

I don't actually think this is a real "problem" just wanted to put it out there to help anyone else who may panic like I did when I saw it like that in the preview. Perhaps I'll try to find the right channels to ping the mailchimp dev team about it.

**Comment by TedGoas** [comment]
@superpowered Yea for sure, good to know! Glad the _actual email sent_ seems to be working. Stinks about the MailChimp preview, but who know what's going on there.
