### ISSUE TITLE
Add Lists

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#167]
**Note to self:** Add bulletproof lists. You built them at work... you already have the code... pop it into the templates.

Here's the code:

```
<ul style="padding: 0; margin: 0 0 15px 0; list-style-type: disc;">
    <li style="margin:0 0 10px 30px;" class="list-item-first">A list item.</li>
    <li style="margin:0 0 10px 30px;">Another list item here.</li>
    <li style="margin: 0 0 0 30px;" class="list-item-last">Everyone gets a list item, list items for everyone!</li>
</ul>
```

**Comment by istvan-ujjmeszaros** [comment]
What can be the problem if the bullets aren't visible in Outlook? I didn't use the Cerberus templates as a base just put this code into an already built email, but I don't see the difference which can cause it to not work in my email (I see the bullets when running the test with the Cerberus template so it is fine).
Is it explained somewhere how this works? Actually I am interested in the button code too as I don't understand why are they looking good in Outlook (I thought that the padding on the <a> doesn't work there but it seems to work just fine).

**Comment by istvan-ujjmeszaros** [comment]
It seems that I was just using a too small left margin (16px instead of the 30px in the template) so they were out of their container.
