### ISSUE TITLE
Gmail IOS App ignoring media queries

### ISSUE THREAD

**Issue by superpowered** [emailmonday/Cerberus#169]
In the cerebrus-fluid template the gmail Ios app ignores everything in the style block if this style is present:

```
 /* What it does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }
```
with:
![img_3841](https://user-images.githubusercontent.com/7035467/39063744-a9a76886-4491-11e8-9aff-26c47a8d33da.PNG)
without:
![img_3843](https://user-images.githubusercontent.com/7035467/39063745-a9b6ba3e-4491-11e8-9766-b37894467483.PNG)

**Comment by superpowered** [comment]
As far as I can tell ` *[x-apple-data-detectors]` does not cause the block to be ignored, even though it's also an attribute selector.

**Comment by superpowered** [comment]
My guess is that this is meant to target the very top level div `.email-container` ?

possible could just be changed to: 
```
 /* What it does: Centers email on Android 4.4 */
       .email-container {
            margin: auto !important;
        }
```

**Comment by TedGoas** [comment]
@superpowered Hmm, using MailChimp? Is there a checkbox somewhere that says **inline CSS**? Does this behavior occur if CSS is not inlined?

**Comment by superpowered** [comment]
@TedGoas As you suspected, it seems to be a Mailchimp specific thing. Using Putsmail.com (and choosing not to inline) I did not get the same issue.

Looking at it a bit more, Mailchimp isn't inlining anything (as far as I can tell) but it does do some "Formatting" automatically, such as combining separate style blocks. And in this process it decided to strip the `"` fom the ` div[style*="margin: 16px 0"] ` causing it to be `div[style*=margin: 16px 0]`, and thus incorrect.

**Comment by TedGoas** [comment]
@superpowered Cool thanks for pointing this out and following up with what was going on in MailChimp. Good to know!
