### ISSUE TITLE
Thumbnail Right, Text Left & Thumbnail Left, Text Right margins in Hybrid Template on iOS 

### ISSUE THREAD

**Issue by cruzr9038** [emailmonday/Cerberus#174]
![img_9014](https://user-images.githubusercontent.com/38994137/39657338-bfb9006e-4fbb-11e8-89d5-b18798bfec4b.jpg)

iOS doesn't seem to be respecting the margin settings in these 2 sections like the desktop clients do. The attached screenshot shows how these sections render on my iPhone 6s on iOS11.

**Comment by TedGoas** [comment]
@cruzr9038 How did you send a test email to your iPhone 6s on iOS11? There is A LOT wrong with that screenshot above, not just the margins. These columns should be stacking, as well as the three column layout just above.

**Comment by cruzr9038** [comment]
It was sent from MS Outook 2013. Good ol’ Word renderer strikes again?

**Comment by TedGoas** [comment]
@cruzr9038 Oh yeah, that'll do it! Outlook will mangle the source code of any email template like this. Since this isn't a bug with Cerberus, I'll close this for now, but am happy to help with any other question you have.
