### ISSUE TITLE
Compatible with Outlook for sending?

### ISSUE THREAD

**Issue by Grappax** [emailmonday/Cerberus#177]
I tested the Hybrid-Version. Looks fine (in Outllook, Gmail, AppleMail...) when I send TO Outlook, but when I send WITH Outlook (no matter if html or .oft), the Mail is not responsive anymore? Can I change this? Thanks!

**Comment by TedGoas** [comment]
@Grappax I'm happy to hear you've had success sending _to_ Outlook (yay! that's hard enough as it is.), but honestly sending properly rendered email _from_ Outlook is not something I plan on supporting. Outlook is the most challenging email client when it comes to HTML/CSS support and from what I can tell, this lack or support extends to sending and forwarding HTML email. Sorry.

Hybrid is the most complicated of the three Cerberus templates, perhaps if you try using a simpler template, you might have some success?

Happy to discuss here further.
