### ISSUE TITLE
Footer info not centered in Outlook web.

### ISSUE THREAD

**Issue by towry** [emailmonday/Cerberus#178]
![2018-05-30 2 33 46](https://user-images.githubusercontent.com/8279858/40703042-8c4e3626-6416-11e8-8995-12001387f566.png)

## Steps to reproduce:

1. Goto https://partner.outlook.cn/owa/
2. Forward the email to yourself.
3. The footer of the forwarded email is not centered.

**Comment by TedGoas** [comment]
@towry I'm unable to reproduce this. **Are you _forwarding_ an email to Outlook OWA?** As opposed to sending a test email directly?

I noticed the font is broken in your screenshot and am wondering if this is not an issue with the Cerberus source code.

**Comment by towry** [comment]
@TedGoas Please see this https://stackoverflow.com/questions/22895272/outlook-web-app-systematically-removes-align-center-attributes 

The outlook web app will modify the email source code. The reason I try Cerberus is because I want to find a email template that compatible with outlook web apps.
