### ISSUE TITLE
Rendering Issues on Samsung Mail Android 6

### ISSUE THREAD

**Issue by barryflammia** [emailmonday/Cerberus#182]
I've noticed your template isn't responsive in Samsung Mail Android 6. Columns seem to push to even widths and email doesn't scale correctly

https://litmus.com/pub/3f915b5

**Comment by TedGoas** [comment]
@barryflammia Hmm, I'm unable to reproduce. I pasted the Hybrid Template code into Litmus and see a different preview (below).

**How did you produce the Litmus preview you linked? Are you sending a test email to Litmus?**

---

This is what I see in Litmus:

![androidsamsung6-vertical-allowed-1366](https://user-images.githubusercontent.com/1172461/40978305-4f742712-68a1-11e8-8340-4955cdfbe9dc.png)

**Comment by barryflammia** [comment]
I'm using the responsive template.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TedGoas** [comment]
@barryflammia Ahh that makes sense now. **Samsung Mail Android 6 doesn't support media queries**, so the columns in the Responsive Template won't stack or scale on narrow screens because it relies on media queries to do so. I suggest using the Hybrid Template if you'd like responsive email on all mobile clients, including Samsung Mail Android 6. It's more complicated, but doesn't rely on media queries to stack columns.

**Comment by barryflammia** [comment]
@TedGoas Thanks for the quick response. I just a post saying it depends whether you're viewing via smtp or exchange. Sent to a colleague and he sees the responsive email. If I get any complaints about the email I've found a way to render the desktop version on Samsung by using the #MessageViewBody .yourclassnamehere { } technique and forcing the email to desktop size.

**Comment by TedGoas** [comment]
@barryflammia yea, I saw some weirdness in your Litmus preview. Eg. the columns didn't stack but text justification changed.

Thanks for narrowing down to the root cause. Sounds like you have a good handle on your own project. Any other questions or ok to close this?

**Comment by barryflammia** [comment]
No, all good thanks
