### ISSUE TITLE
Rendering issue with AOL Mail app

### ISSUE THREAD

**Issue by yagamikira88** [emailmonday/Cerberus#183]
I'm using the fluid template and I noticed that if you use a long full URL link , and that link is long enough to break on a 600px width (or the phone's portrait mode), the email will become unusable (blinking constantly) when viewing on AOL Mail app, as if the app is trying to fit the long URL in the window. The screen blinking will stop if you put the phone in landscape mode.

Any workaround for this?

**Comment by TedGoas** [comment]
> a long full URL link

☝️ Have an example of this? This seems like it would be applicable to a lot of email clients, not just AOL mobile.

**Comment by yagamikira88** [comment]
I've tested this on other mobile email clients (Gmail, Yahoo, Outlook) and long html URLs will break just fine. Only on AOL mail mobile that it will try to fit a long URL in just 1 line (it will not break), causing the blinking rendering issue.

I believe you can replicate this issue by putting a long URL on your fluid template's body.

I'll see if I can upload samples here tomorrow.

**Comment by yagamikira88** [comment]
![aol mail rendering](https://user-images.githubusercontent.com/39956607/41010453-2daf3508-696a-11e8-85f7-8607071643d3.png)

OK so I have attached herein a screenshot of the AOL Mail app rendering on my phone when there's a long URL. Doesn't have to be very long actually, even an 80 character long URL will already cause rendering issue EVEN on iOS! In other words, this issue occurs on both Android and iPhone.

Is there a possible code-fix for this?

**Comment by TedGoas** [comment]
@yagamikira88 I haven't tested this yet, but here's a bunch of CSS properties you can try throwing at this. Maybe one will work?

---

     <span style="display: inline; max-width: 100%; white-space: pre-wrap; -ms-word-break: break-all; word-break: break-all; word-break: break-word; overflow-x: auto;">
        PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS
    </span>

**Comment by yagamikira88** [comment]
Thanks for the info. Just to report to you that " word-break: break-all; " alone fixed this issue in both iOS and Android AOL Mail app.

Maybe you can add that note in documentation to aid people who may encounter that issue.

**Comment by TedGoas** [comment]
Yep, good call. Glad you're sorted out!
