### ISSUE TITLE
Rendering Issue with Outlook 365

### ISSUE THREAD

**Issue by reallygreatstuff** [emailmonday/Cerberus#185]
First off, amazing templates! Thank you!

I edited the cerberus-responsive
[cerberus-responsive Email HTML edited.txt](https://github.com/TedGoas/Cerberus/files/2095521/cerberus-responsive.Email.HTML.edited.txt) for my company. It looks great in Gmail, but Outlook 365, not so much. 

Gmail Render (looks great):
![gmail render](https://user-images.githubusercontent.com/31970277/41312486-2eb8e936-6e55-11e8-881f-bcbededf2299.jpg)

Outlook 365 Render: 
![outlook 360 render](https://user-images.githubusercontent.com/31970277/41312500-36e9e876-6e55-11e8-8f47-2fd4ff20f242.jpg)
- Background color is different
- Footer isn't aligned
- Buttons not fully colored

**Comment by TedGoas** [comment]
@reallygreatstuff if you test a fresh copy of the responsive template, do you see these issues?

**Comment by reallygreatstuff** [comment]
@TedGoas Here's what the unaltered template looks like in Outlook 365: 
- ![outlook 365 - footer messed up](https://user-images.githubusercontent.com/31970277/41320566-524b751c-6e6e-11e8-80d1-97c2a3b2a76f.png)
- ![outlook 365 - footer messed up_2](https://user-images.githubusercontent.com/31970277/41320647-96d831ac-6e6e-11e8-94b0-9787a9f05dc3.png)

- Foot is to the left
- Can't tell if the buttons are impacted because the background is black

**Comment by TedGoas** [comment]
@reallygreatstuff K here's what I can tell from these screenshots.

**Background color is different**
The background color needs to be updated in three locations. Have you updated all three, including [this one](https://github.com/TedGoas/Cerberus/blob/master/cerberus-responsive.html#L232)?

**Footer isn't aligned**
Honestly not sure what's going on there. I can look into it, though am not sure when.
 
**Buttons not fully colored**
Button background colors also happen in multiple places, like [here](https://github.com/TedGoas/Cerberus/blob/master/cerberus-responsive.html#L456) and [here](https://github.com/TedGoas/Cerberus/blob/master/cerberus-responsive.html#L457), have you updated both?

**Comment by reallygreatstuff** [comment]
@TedGoas Had a more technical friend look at the HTML. She was able to troubleshoot/fix. 
![email fixed](https://user-images.githubusercontent.com/31970277/41355051-8f0e2550-6eee-11e8-94f4-c6514c210862.jpg)

Here's the code she used - 
[RNN_Email_HTML.txt](https://github.com/TedGoas/Cerberus/files/2098343/RNN_Email_HTML.txt)
