### ISSUE TITLE
Yahoo mail not showing background image

### ISSUE THREAD

**Issue by Zvika88** [emailmonday/Cerberus#186]
The background image is not shown in yahoo mail. The `background-image:url(..)` section gets a wrapper like this:   
`background-image:url(https://ecp.yusercontent.com/mail?url=.....&t=....&yreqid=......)`

and the image is never fetched by this yahoo wrapper. That section remains blank, and my text, which was supposed to ride on top of the image, is then displayed on top of the button that was supposed to be below the image.

Tested on safari and chrome - same result. Its likely a yahoo mail problem.

Any idea how to overcome that or how else can we place an image in a cell with text on top?
Thanks!
Z.

**Comment by Zvika88** [comment]
Hi Ted, thanks for the quick response and for the template. Yes, the issue occurs with a freshly pulled copy of the template and it persists. Unlike in your screenshot where a space-holder does show, my JPEG which is 680x300px (I adjusted the template for the different size) and is quite rich in content is being eliminated by yahoo in that code. As a stop-gap I may change the design and have the image banner with text below it instead of on top (separate table cells)  but that would be petty. Since its Yahoo's platform that fails here I'll tinker more to see if image size, format etc affect it.   

Or, is there another technique for text on image you would recommend trying?
Best, Z.

**Comment by TedGoas** [comment]
> Yes, the issue occurs with a freshly pulled copy of the template and it persists.

@Zvika88 Do you have a screenshot of this ☝️? I'd like to see how your issue looks.

**Comment by TedGoas** [comment]
@Zvika88 ping! Just want see if you saw my comment above. I still can't repro this.

**Comment by Zvika88** [comment]
Hi Ted, sorry, I'm hanged up with a pending release and a very thorny last minute problem (not related to the planned post-release campaign). Last that I left the planned campaign I simply eliminated the floating text on the image and replaced it with two separate cells, one for the image and one for the text below it. When I'll have some time I'll change it back to capture the screen shot you asked for.  But what that screen shot will show is simply my text, floating on top of the button that was intended to be above the image, and no image at all.

**Comment by TedGoas** [comment]
@Zvika88 Any update on this? I'd like to close this out if it's not a problem with the source code.

**Comment by Zvika88** [comment]
My apologies Ted.
Well, I cannot really explain why but taking the script section from the current template and putting it into my EJS file does work now! If the template (i've been using the hybrid model) didn't change then Its probably me, likely having had some stupid bug, maybe an error in the gulp script creating relative path to the background image or whatever. Sorry for the trouble, and thanks for the template and support.
Best, Z.
