### ISSUE TITLE
Preview Text hack and Gmail

### ISSUE THREAD

**Issue by jeff01101010** [emailmonday/Cerberus#188]
Is anyone else having issues with Gmail stating that the message was clipped when using the preview text hack? The emails are not actually clipped...but when using the preview text section...Gmail states that message has been clipped. This happens even when using just the unaltered template.

**Comment by TedGoas** [comment]
> The emails are not actually clipped...but when using the preview text section...Gmail states that message has been clipped.

@jeff01101010 Can you provide a screenshot of what this looks like?

**Comment by jeff01101010** [comment]
Not sure if this is helpful or not...but I was looking for an open tag or something in the sent email's html. So attached is the html from the gmail message...if that makes sense :-)
[Code_From_Email.txt](https://github.com/TedGoas/Cerberus/files/2177101/Code_From_Email.txt)

**Comment by TedGoas** [comment]
@jeff01101010 many thanks, this _is_ helpful. I haven't experienced this myself and will try to reproduce.

**Comment by TedGoas** [comment]
@jeff01101010 I tested the hybrid email (biggest file size of the bunch), but am having trouble reproducing this:

---

![screen shot 2018-07-10 at 4 20 14 pm](https://user-images.githubusercontent.com/1172461/42535388-3b386c18-845d-11e8-805b-3d69d3a6144e.png)

Old Gmail with personal account ☝️

---

<img width="675" alt="screen shot 2018-07-10 at 4 21 47 pm" src="https://user-images.githubusercontent.com/1172461/42535454-64482274-845d-11e8-8350-a3f070fbcf5e.png">

New Gmail with business account ☝️

---

I didn't find any open tags. Are you still seeing this issue? What kind of Gmail are you seeing this in? How are you sending text emails?

**Comment by jeff01101010** [comment]
Sorry for wasting your time then. I also looked for open tags and didn't see anything. I am see this issue on both the Gmail app for IOS and the desktop version (non-business). Even when I just take the plain Cerberus template (doesn't matter which one) and send it I see this issue.  However, we use a mass mailer software though...so maybe it's something to do with that process...I just don't see anything wrong in that first html file I attached...so I assumed it didn't have anything to do with the mailer software. Thank you for your time.

**Comment by TedGoas** [comment]
No no no! Thank you for bringing this up, it was certainly _not_ a waste of time. I'm wondering if it has something to do with your mass mailer software. If it's not too much trouble, can you send a test email with [Putsmail](https://putsmail.com/tests/new) (or another mass mailer) and let me know if you still see this issue in Gmail?

**Comment by jeff01101010** [comment]
You are correct. When test from Putsmail or Mailchimp the preview text works without a hitch... thank you again for everything.
