### ISSUE TITLE
Max-width Media Query

### ISSUE THREAD

**Issue by VadimBrodsky** [emailmonday/Cerberus#19]
Is there  a specific reason that the `max-width` media query appears twice in the [template-with-media-queries](https://github.com/TedGoas/Cerberus/blob/master/template-with-media-queries.html)?

``` css
 @media screen and (max-width: 600px), screen and (max-width: 600px)
```

**Comment by TedGoas** [comment]
@VadimBrodsky Oops, thanks for catching this. It should read `@media screen and (max-device-width: 600px), screen and (max-width: 600px)`.

I'll fix this post haste! [reference](http://emailwizardry.nightjar.com.au/2013/08/28/media-queries-in-html-email-cover-all-your-bases/)

**Comment by VadimBrodsky** [comment]
Thanks @TedGoas, I thought I was going crazy.
