### ISSUE TITLE
Background Image with Text (hybrid template): Text not centered in Outlook 

### ISSUE THREAD

**Issue by megamanii** [emailmonday/Cerberus#190]
![capture](https://user-images.githubusercontent.com/12531774/42526890-273aec08-8445-11e8-97d0-b005c8ca15c3.PNG)

**Comment by TedGoas** [comment]
![screen shot 2018-07-10 at 4 13 56 pm](https://user-images.githubusercontent.com/1172461/42534997-4801a244-845c-11e8-8848-1c1b53352d3d.png)

@thegreygoose11 I'm having trouble reproducing, I see this ☝️ in Litmus for all Windows Outlook's and Win10 Mail. Is your screenshot from a preview tool (Litmus, Email on Acid) or an actual copy of Outlook? Are you using up to date code?

**Comment by TedGoas** [comment]
@thegreygoose11 I don't have an easy way to test this using a copy of Windows Outlook. Would you mind trouble-shooting this a bit and reporting back?
