### ISSUE TITLE
2 and 3 columns off-center in Outlook

### ISSUE THREAD

**Issue by barryflammia** [emailmonday/Cerberus#191]
Tables are off center in Outlook and Yahoo on the Hybrid email.

![alignment](https://user-images.githubusercontent.com/33750425/42629541-892de58c-85cb-11e8-9ad2-88a962292a25.PNG)

I corrected Outlook by adding align="center" to the mso table.
Yahoo I added align="center" to the mso child table

![alignment-fixed](https://user-images.githubusercontent.com/33750425/42629858-bcc2538c-85cc-11e8-9a6e-3ee7acbe426b.PNG)

Thanks
Barry

**Comment by TedGoas** [comment]
@barryflammia Thanks for pointing this out. Would you like to create d pull request with your proposed fix? Or would you like me to fix?
