### ISSUE TITLE
Unexpected padding shows up in two even column code

### ISSUE THREAD

**Issue by wallyglenn** [emailmonday/Cerberus#192]
In Cerberus Responsive, there is a table in "2 Even Columns" at roughly line 302 and 318. The table has no declared width. 

In the example code, there is a 270px image and text that fills the table cells. If you remove the image and only use text for something simple like an address, the table centers the text block and creates a margin which centers the table. The margin comes from line 67 in the style sheet:

`table {
    border-spacing: 0 !important;
    border-collapse: collapse !important;
    table-layout: fixed !important;
    margin: 0 auto !important;
}`

You can remove the center effect by removing `margin: 0 auto !important;`. However. the behavior of the template breaks if you remove it.

One way to overcome this behavior is to add `width="100%"` to the table: 

`<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">`

In my case, adding the width force the table to operate the expected way. it functions in the template example.

I wanted to offer this as a possible improvement to how this template functions.

**Comment by TedGoas** [comment]
@wallyglenn Hmm, I see your point. I think in addition to adding `width="100%"` to the table, we might need to add a `width="50%"` (or something) to the children to ensure the two columns stay even if if their content is lopsided.

I'll test and report back. Thanks for raising this!
