### ISSUE TITLE
Publish Cerberus package on NPM

### ISSUE THREAD

**Issue by alegout** [emailmonday/Cerberus#193]
Hello TedGoas,

Hope you're fine since #143.

It would be nice if Cerberus was available via [npm repository](https://docs.npmjs.com/getting-started/publishing-npm-packages).

Do you think it will be a possibility soon?

Actually, we must add Cerberus this way in our package.json:

`"Cerberus": "github:TedGoas/Cerberus#3.0.5"`

We must update it manually.
Having the possibility to get it via NPM repository let us the possibility to [easily update Cerberus](https://docs.npmjs.com/files/package.json#version) (if you choose cerberus-tedgoas as your package name, cause cerberus is already taken):

`"cerberus-tedgoas": "^3.0.5"`

^3.0.5 is equivalent to >=3.0.5 <4.0.0 ([node-semver](https://github.com/npm/node-semver))

And Cerberus will be update when we `npm update`

Thank you very much again for your great work 👍 👍 👍 
Alban

**Comment by TedGoas** [comment]
@alegout Sure, can you help by submitting a PR with the appropriate updates to the `package.json` file?

I'd prefer the name **cerberus-email**. Here [my NPM username](https://www.npmjs.com/~tedgoas) if that helps.

**Comment by alegout** [comment]
I updated my package.json and now use `"cerberus-email": "^3.0",` 👍

Thank you!
