### ISSUE TITLE
Not responsive in Android Native email app

### ISSUE THREAD

**Issue by omarbhatti123** [emailmonday/Cerberus#195]
Hi, I want to use the the responsive email template but before I did anything modifications I used tested it on different email clients and found out that it's not responsive. Here are the details

**Phone**: Any Android phone
**App**: Native email app of phone
**Email Address**: Official MS outlook account (it's my work email address)

I am stuck with this since one week. Can any one please help me with this. I used the original code without any changes. Here is the link to the code file
https://raw.githubusercontent.com/TedGoas/Cerberus/master/cerberus-responsive.html

![screenshot_2018-09-03-15-09-45](https://user-images.githubusercontent.com/42938009/44988702-e7425880-af8b-11e8-9e9c-8051fa4af8a2.png)

![screenshot_2018-09-03-15-14-39](https://user-images.githubusercontent.com/42938009/44988788-2e304e00-af8c-11e8-84f4-4dcf9f4ea079.png)

Regards,
Omar

**Comment by TedGoas** [comment]
@omarbhatti123 Hi Omar, not all Android phones/clients support media queries. This may be why you're seeing a desktop version when using the **responsive** template. Have you tried using the **hybrid** template?

**Comment by omarbhatti123** [comment]
@TedGoas Hybrid did the trick. Thanks for your comment and suggestion. Saved my hours.
