### ISSUE TITLE
Placeholder graphics on info site are 404

### ISSUE THREAD

**Issue by solsticesurfer** [emailmonday/Cerberus#197]
The URLs for the placeholder graphics seem to have changed and the current ones are throwing 404s. Looks like placehold.it has changed to placeholder.com and is using a subdomain to host the images, via.placeholder.com

**Comment by TedGoas** [comment]
Hmm I still see placeholder graphics in Chrome. But point taken: placehold.it has changed, so I'll update the references. Thanks!

<img width="711" alt="screen shot 2018-09-17 at 12 01 21 pm" src="https://user-images.githubusercontent.com/1172461/45634890-90e81600-ba71-11e8-8a36-f429c365b1f5.png">
