### ISSUE TITLE
4px below hero image

### ISSUE THREAD

**Issue by tzappia** [emailmonday/Cerberus#204]
There is an extra 4px that the `<td>` around the hero image occupies. Adding `display:block;` to the image takes it away. If you'd like I can open a pull request.

**Comment by TedGoas** [comment]
@tzappia Maybe!

1. Which template? All of them?
2. Which email clients?
3. How much have you tested this to see if adding a `display:block;` impacts the intended design?

**Comment by tzappia** [comment]
1. All templates.
2. In the default clients that Litmus adds to a builder, all but Outlook on Windows showed the issue.
3. I ran the same 16 default clients in Litmus with `display: block;` on the image and none were adversely impacted, and this did resolve the issue.

I'm happy to add more client tests before submitting a PR (well, whatever ones Litmus gives me access to.)
