### ISSUE TITLE
Unintended margin next to Thumbnail left/right

### ISSUE THREAD

**Issue by JorisDebonnet** [emailmonday/Cerberus#205]
In the hybrid template, I believe the "Thumbnail left, text right" (and other way around) has a bug. The Outlook-specific code gives the thumbnail 220px width (to allow 200px image + 2*10px padding), but the div says `max-width: 200px`, resulting in the "200x200" image being resized to 180x180 and extra whitespace appearing left and right.

This can be fixed by making those thumbnail-divs match the Oulook-specific code, e.g. `max-width: 220px`.

(other than that, I LOVE this, so glad I found it.)

**Comment by TedGoas** [comment]
@JorisDebonnet 🤦‍♀️ Good catch and thanks for opening an issue. I'll fix!
