### ISSUE TITLE
Android 4.4 

### ISSUE THREAD

**Issue by robcalcroft** [emailmonday/Cerberus#206]
Hey, i noticed that the Android 4.4 mail client doesn't appear to work responsively and the items don't stack properly:
**Android 4.4**
<img width="494" alt="screenshot 2019-01-28 at 10 41 16" src="https://user-images.githubusercontent.com/3504764/51831233-84aa7a00-22e9-11e9-862c-7b0faaec9c0d.png">

**Gmail**
<img width="568" alt="screenshot 2019-01-28 at 10 41 38" src="https://user-images.githubusercontent.com/3504764/51831242-8b38f180-22e9-11e9-8205-b26e31b2c18a.png">

**Comment by TedGoas** [comment]
@robcalcroft Which template is this?

**Comment by robcalcroft** [comment]
Responsive

**Comment by TedGoas** [comment]
Without know specifically which email client this is, chances are the Android client in question doesn't support media queries whereas the Gmail client you screenshot'd does. 

[This explains a little more](https://litmus.com/help/email-clients/media-query-support/):
<img width="759" alt="screen shot 2019-01-28 at 8 04 18 am" src="https://user-images.githubusercontent.com/1172461/51838128-70f41900-22d3-11e9-84c1-b3db2c515c88.png">

---

If you're looking for a shape-sifting layout everywhere, please try [the hybrid template](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html).

**Comment by TedGoas** [comment]
Happy to discuss if this isn't the case. I'll close this for now ✌️
