### ISSUE TITLE
Replacing Header Images with Larger Image Causes Cropping in Outlook

### ISSUE THREAD

**Issue by arranf** [emailmonday/Cerberus#21]
Removing the line-height:0 fixed this for me.

See:
http://stackoverflow.com/questions/17298867/outlook-2013-cutting-off-top-of-image
http://stackoverflow.com/questions/11201185/images-getting-cut-off-in-outlook-2007-2010

**Comment by TedGoas** [comment]
Hi @arranf, what line(s) of code did you remove `line-height:0` from? Are you using the current version of the templates?

**Comment by arranf** [comment]
Hey @TedGoas.
Sorry for the vague issue. 

I believe I am using the most current version of the template. I removed `line-height:0` from line **165** of the template with media queries.

**Comment by TedGoas** [comment]
@arranf [Is this the line you're looking at](https://github.com/TedGoas/Cerberus/blob/master/template-with-media-queries.html#L165)? If so, this is meant to be a spacer and not hold any content.

**Comment by arranf** [comment]
Two lines below that.

**Comment by TedGoas** [comment]
@arranf Interesting, thanks for pointing this out.
