### ISSUE TITLE
Blue link fix not working for date/time in Outlook iOS

### ISSUE THREAD

**Issue by thomasaustin** [emailmonday/Cerberus#213]
Found that changing * to a on these two classes (*[x-apple-data-detectors], .unstyle-auto-detected-links *) fixed the issue.

![screen shot 2019-02-20 at 9 47 37 am](https://user-images.githubusercontent.com/2408813/53053375-43c31100-34f5-11e9-8f06-2a231a284e0d.png)

**Comment by TedGoas** [comment]
@thomasaustin so...

```
*[x-apple-data-detectors], .unstyle-auto-detected-links *
```

...becomes...
```
a[x-apple-data-detectors], .unstyle-auto-detected-links a
```
?

**Comment by thomasaustin** [comment]
Yes that’s correct. Still might need to test that this change won’t effect anything else though.

**Comment by TedGoas** [comment]
@thomasaustin I'm having trouble reproducing this. (screenshots below)

In your design above, have you wrapped the day/times part in a `<span class="unstyle-auto-detected-links">`?

![img_b92e3f5da09d-1](https://user-images.githubusercontent.com/1172461/53124743-1fcdf280-352a-11e9-9866-a7a3f0f58537.jpeg)
![androidoutlook-vertical-allowed-1366](https://user-images.githubusercontent.com/1172461/53124746-22304c80-352a-11e9-990d-eed43d0d2757.png)

**Comment by thomasaustin** [comment]
@TedGoas I can't see any date or time in your screenshots above? I wrapped 'Mon-Fri 6:00am - 10:00pm' with the unstyle-auto-detected-links span but it still didn't fix it.

![screen shot 2019-02-21 at 8 51 23 am](https://user-images.githubusercontent.com/2408813/53127378-6406d480-35b6-11e9-8bcd-d6f2c4385207.png)

**Comment by TedGoas** [comment]
@thomasaustin sorry for the delay. I was able to reproduce this using your screenshot above and verified your fix. Thanks for catching this!
