### ISSUE TITLE
Missing closing tag in hybrid template

### ISSUE THREAD

**Issue by jorgeluislazo** [emailmonday/Cerberus#214]
I know the template is meant to be used as a base, but just as an FYI.

On line 347, the `<img>` tag is missing a closing bracket. (First image after" 2 Even Columns" section).

If you check out the template as a test on Windows 10 Mail app it will break and show part of the wrapping td tag as text instead.

**Comment by TedGoas** [comment]
@jorgeluislazo Oops! Great catch, thanks for reporting this. I'll fix soon.
