### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by soullivaneuh** [emailmonday/Cerberus#22]
Just found your project, nice work! :+1: 

It would be great to have it on Bower package management: http://bower.io/

You just have to create a little config file and publish it. Can you plan it please? :-)

Thanks!

**Comment by TedGoas** [comment]
@Soullivaneuh thanks for the kind words!

Regarding Bower, I'll keep it in mind. This is the first time it's come up and something I don't use in my own workflow.
