### ISSUE TITLE
Email not centring for outlook.com domains in Samsung Mail Galaxy S10

### ISSUE THREAD

**Issue by thomasaustin** [emailmonday/Cerberus#220]
**Description**
Email not centring for outlook.com domains in Samsung Mail Galaxy S10.

**To Reproduce**
1. Which template? Cerberus Responsive
2. Which email clients and/or devices are affected? Samsung Mail Galaxy S10

**Screenshot**
![Screenshot_20190514-111122_Email](https://user-images.githubusercontent.com/2408813/57670728-e2be5b80-7653-11e9-97c6-48c6bac7ca18.jpg)

**Issue Fix**
Removing auto from margin on html, body in the css reset seems to fix this issue.

`html, body {
      margin: 0 !important;
      padding: 0 !important;
      height: 100% !important;
      width: 100% !important;
}`

**Comment by TedGoas** [comment]
@thomasaustin Thanks for reporting this. I don't have a Samsung Mail Galaxy S10 to test this on, but I removed the `auto` from the reset as you suggested and it didn't seem to break anything elsewhere.

**Comment by thomasaustin** [comment]
@TedGoas I noticed removing auto fixed the email for outlook.com domains on Samsung Mail Galaxy S10 but then other domains for Samsung Mail Galaxy S6 created a left margin, pushing the email off center.

With the code below I was able to correct this and fix both devices.

```
@media screen and (max-width: 600px) {
    #MessageViewBody {
        margin: 0 auto !important;
    }
}
```
