### ISSUE TITLE
Mimecast issue with URLs in comments

### ISSUE THREAD

**Issue by LHDonline** [emailmonday/Cerberus#222]
**Describe the bug**
More of an FYI than a real bug. A change in protocol at Mimecast (a fairly common service which our company uses to filter/scan email for spam) at the end of February broke our Cerberus-based email templates, but only for end-users with Mimecast in place.

After much head scratching and investigation, turns out Mimecast was triggered by the existence of URLs in the code comments, which then caused it to do really bizarre and nonsense rewriting of all of the inline styling in the name of security, and thus breaking the code. Took out the URLs and now no more problem. 

Just wanted to mention it in case anybody else came through with a similar dilemma.

**To Reproduce**
1. Hybrid, but I guess would show up for any of them with same URLs
2. Any email end-user whose email is filtered by Mimecast.

**Comment by TedGoas** [comment]
@LHDonline Hmm, I can see how that could cause an issue. I see URLs [here](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L25) and [here](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L108). Are those the URLs that tripped up Mimecast? Did you have to remove them both?

**Comment by LHDonline** [comment]
TBH, when I was wondering if URLs might be the problem, I just took them both out and didn't test to see which one. What's REALLY crazy is how their software mangled the inline styling 😳 
<img width="1241" alt="Screen Shot 2019-05-07 at 1 03 05 PM" src="https://user-images.githubusercontent.com/7459758/59048771-8f0af080-8854-11e9-8c1f-fde1c3cbeb9c.png">

**Comment by TedGoas** [comment]
I've added a note in the docs about this, thanks again!
https://tedgoas.github.io/Cerberus/#issues
