### ISSUE TITLE
Mobile Margins for 2-column Row

### ISSUE THREAD

**Issue by miamimabel** [emailmonday/Cerberus#223]
Hello - I need help updating the 2-column row, which currently doesn't render on the mobile view to the same width as the single-column (looks fine on desktop). The screenshot of my issue is below.

Thanks in advance for any guidance in updating the code so that the single-column and 2-column align on desktop and mobile.

![hybrid-2-column-row-mobile](https://user-images.githubusercontent.com/44374217/59721218-cc756380-91ee-11e9-82cb-997626872ea7.jpg)

**Comment by TedGoas** [comment]
@miamimabel Can you reproduce this with the original Cerberus template you're using?

**Comment by miamimabel** [comment]
Ted, thanks for the quick reply! I am using the most recent Cerberus hybrid template. All I did was swap the text and image in the 2-column row (my version only has an image on the right side, with all text on the left). 

Below is another screenshot of the original template with the image row and text row swapped, which does not align with the 1-column above it...any ideas on how to make it align?

![cerberus-template-2-column-test](https://user-images.githubusercontent.com/44374217/59724770-064b6780-91f9-11e9-9e80-1e36ea1c9dff.png)

**Comment by TedGoas** [comment]
@miamimabel I can tell the platform is Android, but what email client is this? Outlook?

**Comment by miamimabel** [comment]
This screenshot is from Gmail but it's also happening in Outlook.

Mabel Perez
Manager, State Web Development & e-Communications
Best Buddies International

________________________________

**Comment by TedGoas** [comment]
K I'll take a look. Honestly I'm not sure when I can get to this, though, as I have a vacation upcoming and full plate of work until then.

**Comment by miamimabel** [comment]
Awesome! And I understand. Thank you for your help!

Mabel Perez
Manager, State Web Development & e-Communications
Best Buddies International

________________________________

**Comment by TedGoas** [comment]
@miamimabel Howdy, I finally had a chance to dig into this and think I've found a solution. Better than best, it involves **removing code**.

![Screen Shot 2019-07-16 at 3 10 43 PM](https://user-images.githubusercontent.com/1172461/61322630-219b9980-a7dc-11e9-9d15-6f6db637b4f7.png)

---

It's a little difficult to explain but I'll update the Cerberus templates in the next day or two with the fix.

**Comment by miamimabel** [comment]
Amazing! Thank you so much—you rock! ☺

—

MABEL PEREZ
Manager, State Web Development & e-Communications

BEST BUDDIES INTERNATIONAL
100 SE 2nd Street, Suite 2200
Miami, Florida, 33131
P 305.374.2233 x364  |  F 305.377.1969
BESTBUDDIES.ORG<http://www.bestbuddies.org/>

**Comment by TedGoas** [comment]
@miamimabel I just merged a fresh copy of the Hybrid template.
