### ISSUE TITLE
Outlook app IOS ignoring display:block, columns not stacking

### ISSUE THREAD

**Issue by bwd-adam** [emailmonday/Cerberus#226]
**Describe the bug**
Outlook app IOS ignoring display:block, columns not stacking

**Solution**
Changed `<td>`s to `<th>`s as per https://litmus.com/community/discussions/7658-outlook-app-ios-ignoring-display-block thread

**To Reproduce**
1. cerberus-responsive.html template 
2. Outlook app for iOS (iPhone XS 12.3.1, Outlook app v3.33.0)

**Screenshots**
Screenshots tested of default cerberus-responsive.html v3.2.0 in Litmus app.

![default_Litmus-preview_mobile](https://user-images.githubusercontent.com/53292834/61856649-e567e780-af05-11e9-8ae4-586d8508f1a9.png)
![default_Outlook-iOS_iPhone-X](https://user-images.githubusercontent.com/53292834/61856650-e567e780-af05-11e9-96be-5a69533ddf75.jpeg)

**Comment by TedGoas** [comment]
@bwd-adam Which template is this, `cerberus-hybrid.html` or `cerberus-responsive.html`?

**Comment by bwd-adam** [comment]
Cerberus-responsive.html

Sorry I didn't make file name clear in notes.

**Comment by TedGoas** [comment]
@bwd-adam thanks for clarifying and suggesting the fix. I'll play with this on my end this week (hopefully).

**Comment by bwd-adam** [comment]
No problems, thank you for maintaining a time saving library 🙏 I hadn’t built a mass-market EDM in 5 years, Cerberus got me up to speed and through Litmus testing without the headaches I was expecting.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TedGoas** [comment]
Huh, I'll be damned, I can see this suggestion fixing iOS Outlook.

![Screen Shot 2019-08-12 at 9 14 23 PM](https://user-images.githubusercontent.com/1172461/62908608-e0e56080-bd46-11e9-9ee8-d81602b53589.png)

---

Interestingly enough, Outlook on Android seems to fully support media queries, so this would fix just the one email client.
