### ISSUE TITLE
Full-width body images not rendering on Outlook Desktop for Hybrid template

### ISSUE THREAD

**Issue by miamimabel** [emailmonday/Cerberus#231]
Hello --

I'm using the Hybrid template and my issue is that Outlook Desktop (looks fine on mobile) won't render an image added to the body of my email. I've tried within <p> tags, without, in its own row -- and it keeps cutting it off (see screenshot below) - thanks in advance!

![template-image-issue](https://user-images.githubusercontent.com/44374217/65645463-97cf3000-dfc5-11e9-8d37-0c45491e0632.jpg)

**Comment by TedGoas** [comment]
Can you try removing the `line-height` from both the `<img>` and the parent `<td>`?

**Comment by miamimabel** [comment]
That did the trick, thank you!

—

MABEL PEREZ
Manager, State Web Development & e-Communications

BEST BUDDIES INTERNATIONAL
100 SE 2nd Street, Suite 2200
Miami, Florida, 33131
P 305.374.2233 x364  |  F 305.377.1969
BESTBUDDIES.ORG<http://www.bestbuddies.org/>

**Comment by TedGoas** [comment]
Yay! I'll leave this open as a reminder to fix this in the source files here. I ran into this bug in my own work and fixed it there, but should port that fix here. Thanks!

**Comment by TedGoas** [comment]
After testing this further, it seems this bug is caused by a `line-height` in the image's parent `<td>`. Eg:

```
<td style="font-size: 12px; line-height: 15px;
  <img>
</td>
```

A `line-height` on the image itself seems to be ok as long as their isn't one on the parent `<td>`.
