### ISSUE TITLE
line references are wrong for safely removing for webfonts

### ISSUE THREAD

**Issue by dyspop** [emailmonday/Cerberus#240]
**Describe the bug**
A line in each template tells you which line numbers can be safely removed. They're no longer correct. 

I have made the change locally in a clone of your repo and a new branch but didn't quite see how to submit a PR. Is forking blocked?

**To Reproduce**
1. Which template? all three
2. Which email clients and/or devices are affected? n/a

**Screenshots**

**Comment by TedGoas** [comment]
Resolved in #241

**Comment by TedGoas** [comment]
Forking and submitting a pull request should not be blocked. I see you got it sorted.

**Comment by dyspop** [comment]
yes. i did! i always forget where they keep the fork button separate from the clone button...
