### ISSUE TITLE
Reply/Forward of the mail badly affects the format

### ISSUE THREAD

**Issue by itzrahulsoni** [emailmonday/Cerberus#246]
**Describe the bug**
When you try to forward any mail, it basically destroys all formatting and becomes unusable.

**To Reproduce**
1. All templates are affected. The ones with images are effected more. Just try to hit reply using Outlook or any client.

**Screenshots**
![atto 3](https://user-images.githubusercontent.com/6227719/85680686-26551700-b6e8-11ea-8a20-e078d6ec4d48.png)

**Comment by tedgoas-dialpad** [comment]
@itzrahulsoni Hi Rahul, thanks for opening this. Unfortunately I don't have a great answer for this one. We have little to no control over what email clients do when an email is forwarded or replied to. I'm resigned to the fact that certain email clients will mangle our design and there's little we can do about it. I don't think there's anything I can do about this one 😕

If this is an issue with your project, I would recommend going with a simple design (One column, keep custom spacing and alignment to a minimum, etc.).

**Comment by TedGoas** [comment]
@itzrahulsoni Hi Rahul, thanks for opening this. Unfortunately I don't have a great answer for this one. We have little to no control over what email clients do when an email is forwarded or replied to. I'm resigned to the fact that certain email clients will mangle our design and there's little we can do about it. I don't think there's anything I can do about this one 😕

If this is an issue with your project, I would recommend going with a simple design (One column, keep custom spacing and alignment to a minimum, etc.).
