### ISSUE TITLE
Hybrid email: Random border appearing in Outlook

### ISSUE THREAD

**Issue by RachelRego** [emailmonday/Cerberus#248]
![image](https://user-images.githubusercontent.com/12389765/86600342-edc9fe80-bf6d-11ea-9e0b-a91254b9e8d4.png)

In the hybrid template, a border is appearing to the left of the Thumbnail Right section in Outlook emails.    I've pulled hair out trying to resolve this and ended up just going switching the order of the thumb/content so that it falls beneath the content at mobile size.

**Comment by TedGoas** [comment]
@RachelRego Aye, I've seen this before. I think it's picking up the background of the email's `<body>` tag. Is this screenshot from an actual copy of Outlook? Or a preview tool like Litmus orEmail on Acid?

**Comment by RachelRego** [comment]
The screenshot above is from Litmus but I was able to duplicate the issue in Outlook when building a client email.

**Comment by TedGoas** [comment]
@RachelRego Thanks for the details. I'll dig into this when I can. Presently I don't have access to a Windows machine or a Litmus account, so it may take a while.

**Comment by RachelRego** [comment]
That stinks!  If I can help test anything, let me know!  I rely on your hybrid template for client emails that are mostly in Outlook.  :-p

**Comment by courtnEMAIL** [comment]
I actually was able to get  a fix in place a couple months ago for this issue that seemed to work + test well. 

It basically just creates an outlook on windows only version of the body tag and then you set the  background color to match your email wrapper background color so you can't see the lines anymore. Then, the original body tag is wrapped in the opposite conditional so it appears everywhere else except outlook windows use cases. 

_(note: this is worth a retest though as the build where I figured this solution out was a customised client deliverable "riffed" version of the Cerberus responsive option circa November 2019)_ 

Also - FWIW, none of my live test recipients for outlook windows use cases reported even noticing that the outer background color had changed from one test version to the next  in case that's a worry! 👍 

![carbon (9)](https://user-images.githubusercontent.com/67844663/87213956-f01cc600-c37c-11ea-8a91-1df69683e424.png)

Hope this helps!

**Comment by TedGoas** [comment]
@RachelRego Can confirm this color is coming from the email's background. Here I changed the email background to red:
<img width="792" alt="Screen Shot 2020-11-22 at 9 13 04 PM" src="https://user-images.githubusercontent.com/1172461/99924286-9f907e80-2d07-11eb-9767-860b710614ee.png">

I don't know why Outlook is doing this here.

If it's possible to change the email background to match the container background, @courtnEMAIL's suggestion above is a good one:
<img width="871" alt="Screen Shot 2020-11-22 at 9 16 44 PM" src="https://user-images.githubusercontent.com/1172461/99924374-0e6dd780-2d08-11eb-98de-1ffa9d7ff62a.png">

---

Honestly I'm not sure what to do about this one.

**Comment by joostkalwij** [comment]
I just had the same problem. You can fix it by removing the padding from style in the td that has dir="rtl".
See https://github.com/TedGoas/Cerberus/issues/115
In the contribution RKAN suggested to use a border, which did not work for me. I moved the padding to an element below. It adds some padding to the gutter between the cols, but at least the client is happy that the line is gone.

**Comment by marcelgruber** [comment]
I have also found that some clients cause similar issues when using heading tags. I converted all `<h1>` and `<hx>` elements to be `<p>` instead.

**Comment by antoinegadp** [comment]
I had the same issue.
I try to modify like this :


	        <tr>
	            <td dir="rtl" width="100%" style="padding: 0px; background-color: #ffffff;">
	                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
	                    <tr>
	                        
	                        <th width="33.33%" class="stack-column-center">
	                            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
	                                <tr>
	                                    <td dir="ltr" valign="top" style="padding: 10px 20px;">
	                                        <img src="https://via.placeholder.com/170" width="170" height="170" alt="alt_text" border="0" class="center-on-narrow" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 15px; color: #555555;">
	                                    </td>
	                                </tr>
	                            </table>
	                        </th>
	                        
	                        
	                        <th width="66.66%" class="stack-column-center">
	                            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
	                                <tr>
	                                    <td dir="ltr" valign="top" style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 20px; text-align: left;" class="center-on-narrow">
	                                        <h2 style="margin: 0 0 10px 0; font-family: sans-serif; font-size: 18px; line-height: 22px; color: #333333; font-weight: bold;">Class aptent taciti sociosqu</h2>
	                                        <p style="margin: 0 0 10px 0;">Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
	                                        
	                                        <table role="presentation" cellspacing="0" cellpadding="0" border="0" class="center-on-narrow" style="float:left;">
	                                            <tr>
		                                            <td class="button-td button-td-primary" style="border-radius: 4px; background: #222222;">
														<a class="button-a button-a-primary" href="https://google.com/" style="background: #222222; border: 1px solid #000000; font-family: sans-serif; font-size: 15px; line-height: 15px; text-decoration: none; padding: 13px 17px; color: #ffffff; display: block; border-radius: 4px;">Primary Button</a>
													</td>
	                                            </tr>
	                                        </table>
	                                        
	                                    </td>
	                                </tr>
	                            </table>
	                        </th>
	                        
	                    </tr>
	                </table>
	            </td>
	        </tr>

**Comment by TedGoas** [comment]
@antoinegadp What did you change in that code block?

**Comment by antoinegadp** [comment]
On the first td, i put padding to 0px:
  
td dir="rtl" width="100%" style="padding: 0px;

then i increase the padding here:

First Column:

td dir="ltr" valign="top" style="padding: 10px 20px;">

Second column:

td dir="ltr" valign="top" style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 20px;

**Comment by TedGoas** [comment]
@antoinegadp + anyone else listening to this thread, [I tried fixing this issue](https://github.com/TedGoas/Cerberus/pull/285) if y'all want to test on your end. Thanks!

**Comment by TedGoas** [comment]
I believe [we finally fixed this one](https://github.com/TedGoas/Cerberus/pull/286).
