### ISSUE TITLE
How to vertically center text content on the 2 col

### ISSUE THREAD

**Issue by aikodes** [emailmonday/Cerberus#249]
Using the hybrid template.
How can I centralise the text content for the snippet:

I tried changing `vertical-align` to `middle` on the text div but it is still positioned at the top.

**Comment by TedGoas** [comment]
@aikodes I'm not sure which part of the hybrid template you're referring to. Can you post the full snippet or link the line number of the hybrid template?

**Comment by aikodes** [comment]
The section starts at  line 482 of the cerberus-hybrid.html
https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L482

<img width="1552" alt="Screenshot 2020-07-30 at 9 01 33 PM" src="https://user-images.githubusercontent.com/2247985/88926464-9d159f00-d2a8-11ea-93be-fedd42199715.png">

**Comment by TedGoas** [comment]
@aikodes I believe vertical alignment needs to be changed in a few places to work.

Here are the places it appears (as either `valign` or `vertical-align`):

* [line 485](https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L485) (this one might be enough on its own)
* [line 489](https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L489)
* [line 491](https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L491)
* [line 502](https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L502)
* [line 504](https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L504)

If you switch these values from `top` to `middle`, it _should_ work.

**Comment by aikodes** [comment]
Thanks a lot! 
Had to implement all of those you listed to make it work properly in Outlook 365.
There are other issues but I will post on another issue.
