### ISSUE TITLE
Nested RTL tables & Bulletproof BG on Outlook 365 Windows

### ISSUE THREAD

**Issue by aikodes** [emailmonday/Cerberus#250]
**Describe the bug**
1. Nested tables in the 2 column RTL still inherits the rtl direction. In this screenshot it's the button.
2. Bulletproof backgrounds does not look like it has height declared.
3. Buttons and links are not inheriting text-decoration: none.

**To Reproduce**
1. Which template? (there are three) **Hybrid**
2. Which email clients and/or devices are affected? **Outlook 365 / Windows 10**

**Screenshots**
1. Nested RTL tables 
![error-hybrid-RTL](https://user-images.githubusercontent.com/2247985/89171942-74491e80-d5b4-11ea-91e1-537440baf8d6.jpg)

2. Bulletproof bg
![error-hybrid-bgimagewithtext](https://user-images.githubusercontent.com/2247985/89171975-7f9c4a00-d5b4-11ea-9e18-9d6ab6f3a9b5.jpg)

**Comment by istvan-ujjmeszaros** [comment]
Looks like you didn't add a valid url to the button, and FYI Outlook 365 has a bug and is messing up the HTML DOM with invalid links (like `#`).

**Comment by TedGoas** [comment]
@aikodes Hmm I'm unable to reproduce this one in Email on Acid, this is what I see:
<img width="657" alt="Screen Shot 2020-11-22 at 9 07 48 PM" src="https://user-images.githubusercontent.com/1172461/99924111-e3cf4f00-2d06-11eb-8b47-49747cafca3c.png">

Are you still seeing this issue? Trying to think what could be going on here.

Is the screenshot above from an actual Outlook 365 client on Win10? Or are you using a service like Litmus or Email on Acid?

**Comment by aikodes** [comment]
Closing this as it was an .OFT issue.
It happened when I attached the HTML as text in Microsoft Outlook and sent the tests.
Thanks for checking!
