### ISSUE TITLE
Margin errors and bulletproof BG on Outlook Mac

### ISSUE THREAD

**Issue by aikodes** [emailmonday/Cerberus#251]
**Describe the bug**
1. Margins between paragraphs and buttons (table) are not respected.
2. Bulletproof backgrounds does not look like it has height declared.
3. Buttons and links are not inheriting text-decoration: none.

**To Reproduce**
1. Which template? (there are three) **Hybrid**
2. Which email clients and/or devices are affected? **Microsoft Outlook for Mac Version 16.39 (20071300)**

**Screenshots**
1. Bulletproof BG
<img width="872" alt="error-bgimagewithtext-outlookmac" src="https://user-images.githubusercontent.com/2247985/89172490-50d2a380-d5b5-11ea-9093-237b2e565369.png">

2. Margin errors
<img width="766" alt="error-margins-outlookmac" src="https://user-images.githubusercontent.com/2247985/89172568-7364bc80-d5b5-11ea-8826-6bf5309e1542.png">

**Comment by istvan-ujjmeszaros** [comment]
Looks like you didn't add a valid url to the button, and FYI Outlook 365 has a bug and is messing up the HTML DOM with invalid links (like `#`).

**Comment by TedGoas** [comment]
@aikodes Sorry, I'm between Email on Acid accounts and just got access again. I tested the hybrid template in EoA's version of Outlook 2016OSX 10.8 but don't see what you're seeing. I notice the email is stacking where it shouldn't, but I'm not seeing issues with the background image, the margin issues, or underlined links in the buttons.

Trying to think what could be going on here. Are you seeing this while using Microsoft Outlook for Mac (vs Litmus or Email on Acid)? How are you sending this test email?

**Comment by aikodes** [comment]
Wow thanks for replying.
I can’t remember the exact details as of now since it was a few months ago. I’ll have to dig up what happened. Will update when I get to my Macbook.

**Comment by TedGoas** [comment]
@aikodes Sorry for the lengthy delay, I wasn't able to test since I lost access to Litmus for a spell. Please let me know if you remember what happened.

**Comment by aikodes** [comment]
I finally remembered. In addition to the HTML file, I was required to create an .OFT file.
So I attached the HTML as text in Microsoft Outlook and sent the tests.

I guess this is way out of scope?
No support for OFT?

**Comment by TedGoas** [comment]
Unfortunately I don't know how I'd support that, as I don't have access to a Windows Machine or a version of Outlook that can create .OFTs.

However if MS Windows is your primary target audience, I wonder if you even need to bother with hybrid columns and background images. Can you design something simple and not worry about it being responsive? You can likely recreate many of Cerberus's patterns so they display well in desktop Outlook.

**Comment by istvan-ujjmeszaros** [comment]
Unfortunately, Outlook alters the HTML code in many ways. It is possible to do a bit more complex emails as well but it needs a lot of trial and error. I wouldn't use any VML code in an email that will be sent with Outlook (I, personally, wouldn't use VML in any email at all as Exchange server can be configured to filter out VML, and that filter is just as buggy as Outlook and the end result can be a totally blank email). My suspicion is that on the screenshot, the bug is the result of some HTML or VML opening or closing tag being removed while the pairing tag was left there, causing an invalid DOM document, which then renders bad.

**Comment by aikodes** [comment]
Yeah I guess .OFTs are in their own special category.
Thanks for your replies guys!
