### ISSUE TITLE
full-width-image class

### ISSUE THREAD

**Issue by coldlamper** [emailmonday/Cerberus#26]
What is the purpose of this class applied to some of the tags like 

```
<td class="full-width-image">
```

? The reason I ask is I don't see any corresponding styles defined.

**Comment by TedGoas** [comment]
@coldlamper Thank you for pointing this out; I've already found one instance in the email I'm currently working on. I'll give all three templates a class audit. Please let me know if you find any other superfluous classes.

**Comment by TedGoas** [comment]
@coldlamper Thank you again for pointing out this extra class, I've removed it. I did a quick audit and didn't find any other extraneous classes, but if you find another, please let me know!
