### ISSUE TITLE
Outlook 120 dpi clients do not properly render "Background Image with Text" Hybrid component

### ISSUE THREAD

**Issue by marcelgruber** [emailmonday/Cerberus#260]
**Description**
Outlook 120 dpi clients, most commonly Outlook 2019, seem to have trouble properly rendering the "Background Image with Text" Hybrid component when testing in Email on Acid. 

The HTML I am sending has MINIMAL modifications from the original Cerberus source code.

The issue is more visible when the fill color of this component is a different color than black. What happens is that the background image does not cover the entire fill area, which leaves two "padded" edges on either edge of the text block where the fill color sticks out.

**Screenshots**
![Screen Shot 2021-04-02 at 1 58 55 PM](https://user-images.githubusercontent.com/4956028/113449813-dfedc080-93bb-11eb-9764-8b10fdd880a6.png)
![132039_135818](https://user-images.githubusercontent.com/4956028/113449824-e1b78400-93bb-11eb-85e8-16ed55daf5b4.jpeg)
![Screen Shot 2021-04-02 at 2 25 59 PM](https://user-images.githubusercontent.com/4956028/113451593-85566380-93bf-11eb-9fbb-ce889ef54191.png)

**Comment by marcelgruber** [comment]
If I run "Editor" style tests in Email on Acid, I can also see he issue manifest differently for other Outlook 120 dpi clients:
![132039_141216](https://user-images.githubusercontent.com/4956028/113450753-ba61b680-93bd-11eb-9e5a-4a7d531fa56b.jpeg)

**Comment by TedGoas** [comment]
Aye, this is something I've noticed over the years and haven't been able to solve. Do you have any ideas?

**Comment by marcelgruber** [comment]
If we boil the problem down and ignore Luminate (I removed all Luminate references above to keep this issue focused), yes, I have some ideas. 

I'll aim to add some more comments and perhaps create a PR on Monday.

**Comment by TedGoas** [comment]
+1 let's ignore Luminate.

**Comment by marcelgruber** [comment]
@TedGoas I did further testing, and it looks like the Hybrid template actually passes all of the desktop tests, other than some text getting cut off in the "Background Image with Text" component in Outlook 120 dpi clients The issues in the screenshot above were largely because of Luminate. The fix for the text cutoff issue would be trivial; just increasing the height of the fill image or widening the 500px inner table. However, I do have a PR ready for a new component which should could be a nice addition.
