### ISSUE TITLE
Mailchimp test message - Instruction and personal message

### ISSUE THREAD

**Issue by bobartlett** [emailmonday/Cerberus#263]
**Describe the bug**
When using Cerberus Hybrid, if a user sends a test message and they use _Include instructions and a personal message _, the columns in the body of the email are squashed down and only use about 50% of the screen.

**To Reproduce**
1. Which template? Cerberus Hybrid
2. Which email clients and/or devices are affected? Apple Mail iOS

**Screenshots**
![IMG_5168](https://user-images.githubusercontent.com/1413058/117315722-91fe2980-ae4d-11eb-9575-47b58bbb7fd2.JPG)
![IMG_5169](https://user-images.githubusercontent.com/1413058/117315723-9296c000-ae4d-11eb-9a2b-40c03bb3af68.JPG)
![IMG_5170](https://user-images.githubusercontent.com/1413058/117315727-9296c000-ae4d-11eb-917c-8cf32396177b.JPG)

**Comment by TedGoas** [comment]
@bobartlett Hi, thanks for reporting. Can you reproduce this bug with the original code found in this repo?

**Comment by bobartlett** [comment]
Thanks for following up. It does have the same issue with the original code. I am attaching a screenshot from Litmus as well as the code that Mailchimp sends.

![iphone11-vertical-allowed-1366](https://user-images.githubusercontent.com/1413058/117547737-db3dad00-aff6-11eb-984a-51f348b7990d.png)

[mailchimp-cerberus-fluid.html.txt](https://github.com/TedGoas/Cerberus/files/6446253/mailchimp-cerberus-fluid.html.txt)

**Comment by TedGoas** [comment]
@bobartlett Hi I'm still a little clear what's going on. It looks like something is being added to the top of this template. I don't recognize this part:

<img width="414" alt="Screen Shot 2021-05-09 at 8 01 45 PM" src="https://user-images.githubusercontent.com/1172461/117591229-89357e00-b101-11eb-9156-e6c451a10f56.png">

---

What is "_Include instructions and a personal message _"? Is this something that's being added by you or Mailchimp? It's not part of the original template.

**Comment by bobartlett** [comment]
Your are exactly right. In Mailchimp, when sending a test message, you can
add a personal message to the recipients. Mailchimp adds the message before
the body of the template.

It is certainly an odd case.

**Comment by TedGoas** [comment]
Ahh ok, so it's not an issue with this template code, but with how Mailchimp adds something to it. Are you able to choose where this message goes? You can certainly write your own message by using one of Cerberus's patterns instead of Mailchimp.
