### ISSUE TITLE
Responsive Problem

### ISSUE THREAD

**Issue by skrshawon** [emailmonday/Cerberus#267]
I use Cerberus framework for my email template. But its responsiveness isn't working for Gmail. How can I fix this Issue?
See the screenshot Click This Link: https://i.imgur.com/eIpJQOi.jpg

**Comment by TedGoas** [comment]
Which template are you using in this screenshot? Many versions of Gmail don't support media queries, so `cerberus-responsive.html` won't work. If you're not already, use `cerberus-hybrid.html`.

If you *are* already using the hybrid template, can you give me more information about what's going on?
1. Have you edited the code in any way?
2. How are you sending the test email to Gmail?
3. Which version of Gmail? And on what device?

---

This is what I see in Email on Acid for Pixel Gmail in Android 8:
![image](https://user-images.githubusercontent.com/1172461/126066976-3a2fd7db-1389-4830-bff2-8e75197fea33.png)

**Comment by skrshawon** [comment]
I use
