### ISSUE TITLE
Question regarding css styles

### ISSUE THREAD

**Issue by andreimoment** [emailmonday/Cerberus#40]
@TedGoas,

We are in the process of building a new set of email templates and will be using Cerberus/hybrid as the base (thank you for it!).

Noticing the two sets of style rules, CSS Reset and Progressive Enhancements, I am wondering if they should be excluded from inliners like Premailer?

My instinct is to inline the CSS Reset and exclude the Progressive Enhancements as they contain media queries which I read as a sign to leave that set along. 

Is this how you intended these?

Also, would you be available for short-time consulting (2-5h) in the next two weeks? 

Let me know.

Andrei

**Comment by TedGoas** [comment]
@andreimoment Cerberus doesn't need an in-liner. The resets are global resets mostly for things that email clients try to do to emails (outside of Cerberus's code), so inlining them wouldn't have much an impact. I'd recommend against inlining Cerberus's default CSS, if possible.

I will respond to your last inquiry via email and leave this issue open if you have any other technical questions.

**Comment by TedGoas** [comment]
@andreimoment Hi Andrei, hope you're having a bit of luck bending Cerberus to your will. Since I haven't heard any further questions here or via email, I am going to close this issue. Feel free to open another or or ping me on email or [twitter](https://twitter.com/TedGoas).
