### ISSUE TITLE
Modifying Three Columns to Four

### ISSUE THREAD

**Issue by mrfseattle** [emailmonday/Cerberus#41]
I'm hoping I can modify the Cerebus Hybrid file to show Four Even columns on Outlook, then breakpoint to Two columns on Tablet, then One column on mobile phones. Any thoughts or tips on that? Thanks!

**Comment by TedGoas** [comment]
@mrfseattle Hmm, that's a tall order for hybrid. I haven't run into this one yet. If you _really need_ this scenario to work in a hybrid sense (meaning you can't use media queries to enforce tablet and phone breakpoints), I would start by taking the `<!-- Two Even Columns -->` code pattern and halving every min/max/width value.

**Comment by TedGoas** [comment]
@mrfseattle Hi Mark, have you made progress on the four-col hybrid pattern?

**Comment by mrfseattle** [comment]
Some progress, will post my results in the next few days. My company
requires a 4-column price list email, so I'm working at making it more
modern and usable. It's a beast for sure. Many thanks!

_Mark Field_
425.770.0287 mobile
mrfseattle@gmail.com

**Comment by TedGoas** [comment]
@mrfseattle Hi Mark, any update on the four-col hybrid pattern?

**Comment by TedGoas** [comment]
@mrfseattle Hi Mark, any update on the four-col hybrid pattern? If not, I'd like to close this for now. Lemme know!

**Comment by mrfseattle** [comment]
No, haven’t been able to get back to it. It’s been a pet project. Hopefully in a month or so I can revive it and finish it of. I’ll be sure to share my results. Thanks for the interest and providing your code to experiment with!

Mark Field
mrfseattle@gmail.com
425.770.0287

**Comment by TedGoas** [comment]
@mrfseattle Thanks Mark! If you're still working on it, I'll leave this open. Cheers!

**Comment by TedGoas** [comment]
@mrfseattle Hi Mark, any update on the four-col hybrid pattern?

**Comment by mrfseattle** [comment]
Hi Ted,
I had gotten this far, and testing on Exact Target showed the Outlooks were collapsing the four product text columns until they were overlapping. See file. I'm re-looking now to see if it works better in the Responsive template. I've got a 60% Outlook viewership, but trying to help out everyone.
And, yes it is an ugly beast of an email that I send every Monday at 5am PST.  ;^}

[cerberus-hybrid-REVISED.html.zip](https://github.com/TedGoas/Cerberus/files/249554/cerberus-hybrid-REVISED.html.zip)

**Comment by TedGoas** [comment]
@mrfseattle I just popped your code into Litmus and it looked ok in the Windows Outlook. Could Exact Target be mangling your code somehow?

As an example, here's what I see in Outlook 2010 via Litmus:
![ol2010-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/15033557/df8cddc8-1239-11e6-8ead-f9bb04fc2518.png)

**Comment by mrfseattle** [comment]
It's possible. I re-ran their Inbox Preivew test on it, and it seemed to
hold up. Though Outlook 2007, 2010 and 2013 were ignoring the line-height
CSS rules and valign="top" for the product color names and the red price
points.

Previously, the Inbox Preview results (just gives .jpeg shots) looked
better than my actual test PC running Windows and Outlook 2013. I'm making
some font stack changes to help spacing then will re-test.

_Mark Field_
425.770.0287 mobile
mrfseattle@gmail.com

**Comment by TedGoas** [comment]
@mrfseattle padding the line-height aside, does the hybrid column stack work while holding true in Windows Outlook?

**Comment by mrfseattle** [comment]
Yes, seems I can't get too tricky with line heights -- was trying to set
(typographic) Leading to line up the colors and prices. May have to punt
that idea. Otherwise, Outlook seems to do ok. Gmail on Android has trouble
and overlaps the columns, not sure why.

_Mark Field_
425.770.0287 mobile
mrfseattle@gmail.com

**Comment by TedGoas** [comment]
@mrfseattle but it seems as though you've solved the four-col hybrid pattern, yes?

**Comment by TedGoas** [comment]
@mrfseattle Mark, have you tried [this code](https://github.com/fcarneiro/tedc15_template/blob/master/scaffolds/4_column_scaffold_centering.html)? It should be exactly what you're looking for if you haven't figured it out already.

**Comment by mrfseattle** [comment]
Interesting, will give it a try later this week. Many thanks!

_Mark Field_
425.770.0287 mobile
mrfseattle@gmail.com

**Comment by TedGoas** [comment]
@mrfseattle Hi Mark, I'm not sure about moving a 4-col pattern into Cerberus but would like to know if you got it working in your own work.

**Comment by mrfseattle** [comment]
Seems fine in test, but haven't rolled it out to customer sends yet.
Working on a proposal to change how we communicate this price content to
them - do they actually find having 90+ products in a list form useful.
Hard to know.

Many thanks!

_Mark Field_
425.770.0287 mobile
mrfseattle@gmail.com

**Comment by TedGoas** [comment]
Hi @mrfseattle, happy to hear you're making progress! 

Your original issue was a question about how to "modify the Cerebus Hybrid file to show Four Even columns on Outlook, then breakpoint to Two columns on Tablet, then One column on mobile phones". Sounds like Cerberus has helped, and I provided [an additional code sample](https://github.com/fcarneiro/tedc15_template/blob/master/scaffolds/4_column_scaffold_centering.html).

However I'd like to defer moving a 4-col pattern into Cerberus and complicate the code for others. **So I propose closing this issue.**

I don't want to leave you high and dry. The issue will, of course, [live on in GitHub](https://github.com/TedGoas/Cerberus/issues?q=is%3Aissue+is%3Aclosed) and we can continue our discussion there. But I'd prefer to take this issue out of Cerberus's development pipeline.

**Comment by mrfseattle** [comment]
Sounds great. Many thanks again for your generosity of time and expertise!
I'll let you know if this makes it to deployment.
Mark
