### ISSUE TITLE
Table banding

### ISSUE THREAD

**Issue by smallpirate** [emailmonday/Cerberus#46]
Would I be correct in assuming that I'd need to nest in a new set of 100% width tables to achieve full-width banding within the sections?

**Comment by TedGoas** [comment]
@jenarmstrong Yes, that would be one way to do it! Using the Hybrid template as an example, copying the `<table>` starting at [line 148](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L184) and ending it after the closing `<tr>` on [line 217](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L217) should give you a single edge-to-edge row to work with. Does that make sense?

**Comment by smallpirate** [comment]
Yes, makes sense and worked well. Thanks for the peace of mind!

**Comment by TedGoas** [comment]
@jenarmstrong Awesome, let me know if you run into any issues or have other questions. Cheers!
