### ISSUE TITLE
Bug visualization on samsung s6/s6 email app

### ISSUE THREAD

**Issue by metalgigio** [emailmonday/Cerberus#48]
I'm italian so i'm sorry for my english.
I've discovered that hybrid template have an ugly right band when viewing on samsung s6/s7 email app.
I've made some test and i've also discovered that changing:

```
html,
body {
            margin: 0 !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }
```

to

```
html,
body {
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }
```

solved the issue.
Hope it can help

**Comment by TedGoas** [comment]
@metalgigio thanks so much for flagging this? Any chance you have before / after screenshots?

**Comment by TedGoas** [comment]
@metalgigio Thanks so much for uncovering a bug. I don't have a samsung s6/s7 email app to test on. I tested the code above but found that it breaks the margins on the Android 4.4 stock email browser. **Have you experienced this?**

![android4-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/14591584/1046b6c4-04e2-11e6-953d-74aa48b18999.png)

**Comment by metalgigio** [comment]
Hi,
i will post a screenshot asap.

**Comment by metalgigio** [comment]
Before:

![screenshot_20160418-092253](https://cloud.githubusercontent.com/assets/785743/14596595/c0ddff0a-0547-11e6-863f-3c1beef57e88.png)

After:

![screenshot_20160418-092331](https://cloud.githubusercontent.com/assets/785743/14596598/c87e5a20-0547-11e6-8622-f169f21e6b48.png)

**Comment by TedGoas** [comment]
@metalgigio thanks for pointing this out. I did some testing and found only resetting the `body` margin is necessary, so I separated `html` and `body` resets. Please let me know if your issue persists.

**Comment by metalgigio** [comment]
Hi, the solution u provide did not solve the bad visualizzation on s6/s7.

**Comment by TedGoas** [comment]
@metalgigio Does this code fix it on your device?

Change this:
`html,
     body {
          margin: 0 !important;
          padding: 0 !important;
          height: 100% !important;
          width: 100% !important;
     }`

to this:
`body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }`

**Comment by metalgigio** [comment]
Yes, it works.
i've even tried this code that works correctly too:

html, body { margin: 0 auto !important; padding: 0 !important; height: 100% !important; width: 100% !important; }
