### ISSUE TITLE
Email Not Centered in Yahoo! web mail

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#51]
Regarding [this conversation](https://twitter.com/dlc3172/status/733124633428414464). Litmus shows a centered version, but testing in actual Yahoo mail reproducers the bug.

![screen shot 2016-05-19 at 8 35 39 pm](https://cloud.githubusercontent.com/assets/1172461/15413740/706f1554-1e01-11e6-9abc-2154ca0d9353.png)

**Comment by TedGoas** [comment]
Thanks to @kevinmandeville, who found the trouble maker:
<img width="240" alt="screen_shot_2016-05-20_at_11 46 58_am_480" src="https://cloud.githubusercontent.com/assets/1172461/15450143/32e15226-1f62-11e6-900a-c412279519c0.png">

**Comment by jenn-86** [comment]
Yahoo seems to be having centering issues again.

Taking a fresh version of the current hybrid code and running it through litmus screenshot tests shows it's left aligning the main table and removing the background color.

![image](https://user-images.githubusercontent.com/39985948/60634401-e5bf1680-9e62-11e9-8ac5-2138ebe41107.png)

**Comment by TedGoas** [comment]
@jenn-86 Hmm, strange, I see it too. It's like Yahoo isn't making the `<body>` full width :/

![Screen Shot 2019-07-03 at 11 11 40 PM](https://user-images.githubusercontent.com/1172461/60637317-fed6b180-9de7-11e9-8b26-b9c586732024.png)

---

I'll take a look!

**Comment by TedGoas** [comment]
Appears Yahoo made a change that resurfaced an old bug:

![Screen Shot 2019-07-09 at 5 18 42 PM](https://user-images.githubusercontent.com/1172461/60923795-ac751500-a26d-11e9-9e43-2d2745ae52fb.png)
(from an email slack group I'm in)

**Comment by TedGoas** [comment]
Yahoo may have fixed it or rolled it back their end, though. I just went to fix this and noticed that Litmus isn't displaying the bug anymore:

![image](https://user-images.githubusercontent.com/1172461/60924186-8dc34e00-a26e-11e9-813a-e62b6bfca834.png)

**Comment by jenn-86** [comment]
Fixed for me now too without changing my code... Thank you for looking into it!
