### ISSUE TITLE
600px email width Outlook 2016

### ISSUE THREAD

**Issue by Baswazz** [emailmonday/Cerberus#53]
Problem with the 600 max-width on Microsoft Outlook 2016.

![cerb](https://cloud.githubusercontent.com/assets/1690629/15849037/a59cbd2e-2c90-11e6-9154-36a01217fde5.jpg)

Is there a fix?

**Comment by TedGoas** [comment]
@Baswazz I'm having trouble reproducing this. I don't have Windows 10, but I pasted an image of what I see this in Windows 7 Outlook 2016 below. 
1. What version of Windows are you using?
2. What version of Cerberus are you using?

![ol2016-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/15879633/0457047e-2cf4-11e6-90c0-696969769730.png)

**Comment by Baswazz** [comment]
I had trouble reproducing it as-well. The version i use is Windows 10.
Downloaded from Modern.ie.

Under tools you have virtual machines.
I downloaded one for Virtualbox and installed the trail version of Office 2016/Outlook2016

Edit: I used the download zip button on the website en used the cerberus-fluid.html.

**Comment by ebendrum** [comment]
I had the same issues, but the problem can be really quickly solved ;) 

Update your Office 2016 and it will work correctly.

**Comment by TedGoas** [comment]
@Baswazz have you tried @ebendrum's suggestion?

**Comment by Baswazz** [comment]
Downloaded the trail version 2 days ago, I assume it is the latest version.
The version i am running is 16.0.6868.2067

When i try to run windows update it says: Your device is up to date.

**Comment by ebendrum** [comment]
Check if your Windows-Update is configured to update other Microsoft products too. You can find it, in the advanced settings for Windows Updates.

**Comment by Baswazz** [comment]
Give me updates for other Microsoft products when I update Windows is checked.
When i check office-account in outlook it says Updates are automaticaly downloaded and installed.

Install Virtualbox and Windows 10 stable from mondern.ie and install the office 2016 trail version and you will be able to reproduce the problem.

**Comment by TedGoas** [comment]
@Baswazz do all three templates expand to full width in your version of Outlook 2016? or just `cerberus-fluid.html`?

**Comment by TedGoas** [comment]
^^ @Baswazz just wanted to make sure you saw my question above. I haven't heard anyone else experiencing this issue and I can't reproduce this on my end.

**Comment by Baswazz** [comment]
Yes i saw it. I gave you the info to reproduce it. It is on all templates. I now use Foundation Email.

**Comment by kiammiki** [comment]
I used this tool with cerberus' code
https://templates.mailchimp.com/resources/inline-css/
and the error was corrected also in Outlook 2016!
