### ISSUE TITLE
Outlook 2007/2010 "23.7 Inch" Bug

### ISSUE THREAD

**Issue by longjasonm** [emailmonday/Cerberus#55]
Just ran into this while building an email for a client: https://www.emailonacid.com/blog/article/email-development/horizontal_spacing_issues_in_outlook_2007_and_2010

Was able to solve it by removing the 100% `<table>` immediately after the `<body>` tag and did not see adverse effects in any clients.

I know you are always in pursuit of clean code; maybe we remove that outer table?

**Comment by TedGoas** [comment]
@longjasonm Hi Jason, yes always looking to simply (read: delete) code!

Can you describe the issue you ran in a bit more detail? What did you see before? What clients did you retest after the fix?

As per your suggestion, I removed the `width="100%"` on [this line](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L152), but unfortunately that removed the center alignment in Outlook 2007 / 2010. This is what I see:

![ol2007-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/16137929/562f04c2-3406-11e6-9e33-87ea45b6f61c.png)

**Comment by longjasonm** [comment]
Check out my code here...actually delete the entire `table` on line 152 of cerberus-hybrid.html: https://litmus.com/builder/63a28a8 Notice there is no "black line" caused by the 23.7in bug (on your screenshot above, see the break before thumbnail left/text right).

**Comment by TedGoas** [comment]
@longjasonm Great, I can reproduce that and see how it works. All email clients remain centered and no unwanted gaps in Outlook.

This created an issue for a few of the desktop emails losing their background color; I knew I had this code in there for a reason!). But simply adding `background: #222222;` to the `<center>` tag restores it across clients.

![chromegoogleapps-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/16139521/4ca2aac0-3416-11e6-9bc8-34dfa99c7c3c.png)
