### ISSUE TITLE
In the hybrid template there is a padding issue with two same-width column layout

### ISSUE THREAD

**Issue by kwalkerm** [emailmonday/Cerberus#58]
The table that defines the second column doesn't have attributes: `cellspacing="0" cellpadding="0" border="0"` This leads to some odd alignment behavior. This is on line 291 of cerberus-hybrid.html. It is `<table width="100%">` and should be `<table cellspacing="0" cellpadding="0" border="0" width="100%">` like the first column.

**Comment by TedGoas** [comment]
@kwalkerm Thanks for pointing this out. I can clean this up!

> This leads to some odd alignment behavior.

Can you describe the odd alignment behavior? In which email client(s)? Just curious.

**Comment by kwalkerm** [comment]
Love this template btw. I looked for a long time and this was exactly what
we needed. Thanks for putting it together.

The two columns don't line up exactly right. The second column is two
pixels lower than the first. I didn't test it broadly but here is what I
saw. It worked correctly with no alignment issues on Gmail, but if I
forwarded the email from Gmail it showed up. It also showed up the first
time if it was a Gmail for work address. Didn't test other clients.

You can the misalignment in this image (not sure if the image will come
through):

​

**Comment by kwalkerm** [comment]
https://s3-us-west-1.amazonaws.com/joymode/email_aligment_issue.png

**Comment by TedGoas** [comment]
@kwalkerm Well snap, that's a bug. Thanks for pointing it out and describing a way to reproduce!
