### ISSUE TITLE
Custom Tags in Footer?

### ISSUE THREAD

**Issue by harvest316** [emailmonday/Cerberus#59]
Hi Ted.

Thanks for your continued support for this important project.  Subject to further testing, I'm excited about getting my dev team to base all future campaigns on this.

What EDM system is the consumer for the `<webversion>` and `<unsubscribe>` tags in the footer?  Don't we need to add xmlns namespace attributes up the top for these?  Might be better to use generic html tags for these.

I'd also like to add a few more instructions for newbie email programmers, such as "Add custom style block here" so they don't go sticking their CSS before the CSS reset, for example.  I'm making a few trivial edits such as this that I'll commit soon for your review.

Thanks for being awesome,
Paul

**Comment by TedGoas** [comment]
@harvest316 Thanks for the kind words.

Regarding the footer tags, those are from [Campaign Monitor](https://www.campaignmonitor.com). I used them because they are so semantic/obvious and makes it easy to test these templates. Feel free to suggest, but folks (including me) seem pretty happy with them as-is.

I'm intrigued by your suggestion of more instructions, as it would help more folks [understand this code](http://tedgoas.github.io/Cerberus/#contribute)!

**Comment by harvest316** [comment]
Thanks Ted.  Yeah, I might have gotten a little over enthusiastic.  Spent the whole day pouring over your code yesterday. ;)

Being somewhat new to EDM coding, I've compiled a summary of [Email Coding Best Practices](https://workflowy.com/s/n5F3ygomaM) from the leading players like CampaignMonitor, MailChimp, FreshMail, Litmus, EmailOnAcid, etc.  I'd appreciate your edits.  (Unfortunately my team are constrained to a frightfully old EDM called MarketFirst (ugh) so ignore said references.)

Most of my changes to your hybrid template are trivial, or just commentary for junior programmers.  I've also uniquified the lorem ipsum, to allow for the old "search the code for that phrase" method.  Will run it through EmailOnAcid then commit later today, with any luck.  Very much looking forward to your feedback.  :)

**Comment by TedGoas** [comment]
Excellant, I'm looking forward to seeing your suggestions. Overall for Cerberus, I'm most interested in:
1. Fixing stuff that's broken (d'uh)
2. Reducing the amount of code
3. Improving the documentation and explanations (sounds like what you have in mind)

**Comment by harvest316** [comment]
Coolio.

Hey, I'm seeing you open the IE ghost tables with [if mso] but close them with [if (gte mso 9)|(IE)] so we'd be starting tables but not finishing them in early versions of IE.  Not that I care about IE6 but I'll set both to [if mso] in my tweaked version, for consistency.  Just let me know if this was an intended workaround.

**Comment by harvest316** [comment]
I decided to leave it and just raise it as a separate issue.
