### ISSUE TITLE
Template-default 3 column issue

### ISSUE THREAD

**Issue by endofgeneric** [emailmonday/Cerberus#6]
Hi there thanks for the awesome templates. First off, I'm a designer who is html/css savvy and not a developer. I'm having an issue with the 3-column section of the 'template-default' file.

I've removed the padding so the images touch the edge of the wrapper table and added placeholders that are 190px wide, looks fine in both regular and responsive layouts:
![desktop](https://cloud.githubusercontent.com/assets/10222506/5485810/bf856d8a-8697-11e4-8967-d333803357b3.PNG)

![600px-moretextcontent](https://cloud.githubusercontent.com/assets/10222506/5485833/e9543100-8697-11e4-8efc-27cf56c864c4.PNG)

Funny thing is happening though when I remove text from the columns. For example, if I delete a sentence of the dummy copy, I get a gap on the right hand side when I hit the 600px threshold to a responsive layout:

![600px-lesstextcontent](https://cloud.githubusercontent.com/assets/10222506/5485866/354d71b6-8698-11e4-990d-4b5b06a3c375.PNG)

It may be a simple solution but I can't work out what's breaking, any ideas? Here's the code I'm using for the section, all other code - css etc. - has been kept the same in the template:

```
  <tr>
    <td>
      <table border="0" cellpadding="0" cellspacing="0" class="columns-container">
        <tr>
          <td align="center" width="190" style="font-family: sans-serif; font-size: 16px; line-height: 22px;padding-right: 15px;color: #444444;" valign="top" class="force-col">
            <img src="3col-plchldr-190x220.jpg" alt="alt text" height="220" width="190" border="0" style="display: block;padding-bottom: 10px;" class="col-3-img-r">
            <a href="#" style="color:#444444; font-weight:bold; text-decoration: none; text-transform: uppercase;">header</a>
            <br>
            Saepe scaevola id has. Duo et regione albucius ponderum. Dicta definitiones sed ex.
          </td>
          <td style="font-size: 0; line-height: 0; display: none;" class="hh-spacer">&nbsp;</td>
          <td align="center" width="190" style="font-family: sans-serif; font-size: 16px; line-height: 22px; padding-right: 15px;color: #444444;" valign="top" class="force-col">
            <img src="3col-plchldr-190x220.jpg" alt="alt text" height="220" width="190" border="0" style="display: block; padding-bottom: 10px;" class="col-3-img-l">
             <a href="#" style="color:#444444; font-weight:bold; text-decoration: none; text-transform: uppercase;">header</a>
            <br>
            Saepe scaevola id has. Duo et regione albucius ponderum. Dicta definitiones sed ex.
            </td>
          <td style="font-size: 0; line-height: 0; display: none;" class="hh-spacer">&nbsp;</td>
          <td align="center" width="190" style="font-family: sans-serif; font-size: 16px; line-height: 22px;color: #444444;" valign="top" class="force-col">
            <img src="3col-plchldr-190x220.jpg" alt="alt text" height="220" width="190" border="0" style="display: block;padding-bottom: 10px;" class="col-3-img-r">
             <a href="#" style="color:#444444; font-weight:bold; text-decoration: none; text-transform: uppercase;">header</a>
            <br>
            Saepe scaevola id has. Duo et regione albucius ponderum. Dicta definitiones sed ex.
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <!-- Three Column ==> Stacked Wide Layout ==> Stacked Narrow Layout : END -->
```

Thanks!

**Comment by TedGoas** [comment]
@endofgeneric Heya, I just released a new version of Cerberus. If you're still having trouble and can recreate the same issue above with the new code, can you please file a new bug? For now, I'm going to close this issue since the code your working with is moving towards deprecation.

If you have any questions, hit me up here or on Twitter @tedgoas.

**Comment by endofgeneric** [comment]
Thanks for the heads up Ted. I'll take a look at the updated version and let you know of any issues I have. 

Thanks!

## Michael Clayton
