### ISSUE TITLE
Not closing ghost tables in early IE

### ISSUE THREAD

**Issue by harvest316** [emailmonday/Cerberus#62]
Looks like we open the IE ghost tables with [if mso] but close them with [if (gte mso 9)|(IE)] so we'd be starting tables but not finishing them in early versions of IE.

**Comment by TedGoas** [comment]
Thank you!! Sorry I guess we submitted similar issues around the same time. I [committed a fix for this](https://github.com/TedGoas/Cerberus/commit/7bd1bfcaa185b19b42665a45f237aa0c7275fa0e).
