### ISSUE TITLE
Inconsistent width 600px on cerberus-responsive.html

### ISSUE THREAD

**Issue by harvest316** [emailmonday/Cerberus#66]
...the others are 680px

**Comment by TedGoas** [comment]
Hybrid is 680px so the "fragile" hybrid grid works. The other two templates can be any width and still work as intended. Hmm, you raise a good point about the inconsistency. On the other hand, I wouldn't want to edit the other two based on the limitations of the Hybrid template.

Perhaps this is where some code comments explain this?
