### ISSUE TITLE
Background image isn't vertically centering in Outlook.com

### ISSUE THREAD

**Issue by harvest316** [emailmonday/Cerberus#69]
The background image isn't vertically centering in Outlook.com, and Outlook 2016 (Win) has text overlapping in the same section, though I'm yet to verify this on a real Outlook 2016 instance. Screenshots: https://www.emailonacid.com/app/acidtest/display/summary/x8nb1jDUYrxfgars3BsQQLULDUMWf8cpMP1dlxsa3bPDI/shared

**Comment by TedGoas** [comment]
I haven't been able to fix this one yet, but I found some information about how others have worked around this issue.

TL;DR: seems like folks are using absolute positioning using `<v:>` attributes such as `position` and `style`. Check out this beast from [this post]:(https://www.campaignmonitor.com/forums/topic/7896/background-centered-on-outlook-with-vml/).

```
<v:image xmlns:v="urn:schemas-microsoft-com:vml" id="theImage" style="behavior: url(#default#VML); position:absolute; height:1000px; width:1200px;mso-position-horizontal:center;mso-position-horizontal-relative:text; top:19px; z-index:-1" src="http://www.yourserver.com/backgroundimage.jpg" />
```

This makes me wonder if the only way to enforce vertical alignment in MSO Outlook's to to handle them on a case by case basis.

What has been your experience? Any hack been working well for you?

**Comment by harvest316** [comment]
I'm not sure, but if VML works so well for buttons, maybe we should be using it here too...

**Comment by TedGoas** [comment]
We _are_ using VML here. It's displaying the background image, just not centering it properly.

**Comment by TedGoas** [comment]
I tried a bunch of things that didn't work. I added `mso-position-horizontal:center;mso-position-horizontal-relative:text;`, changed `<v:fill>` to `<v:image>`, absolute positioning and `background-position` on the VML references. Nothing! I'm stumped.

Have you gotten anything to work?

**Comment by fermin-silva** [comment]
Unfortunately I do not have a Windows machine to test, but what about sending an email from the outlook desktop app to yourself, aligning the image with it's built in editor and checking the source it produces?

If that's what you've been doing to fix this, then you can dismiss this message

**Comment by TedGoas** [comment]
@fermin-silva That's an interesting idea. I hadn't been doing that, thanks for sharing!

**Comment by TedGoas** [comment]
After reading these [two](http://blog.two-uk.com/2016/09/14/bg_images_p2/) [articles](http://blog.two-uk.com/2016/09/19/vml_gradient/), I'm not sure it's possible to center-align a background image in "MS Office" Outlook + Outlook.com. One option design an image so it looks ok without being positioned (desktop only, of course). Another option is to turn off the background image in Outlook.com / Outlook 2016 in favor of a solid color.
