### ISSUE TITLE
Add <table role="presentation">

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#71]
[Mark's TEDC 16 presentation, slides 10-13](http://www.slideshare.net/M_J_Robbins/understanding-email-hacks-litmus-live-london-tedc16)

**Comment by TedGoas** [comment]
**Problem:**
_Layout Tables that are read as Data Tables_
Seems this attribute helps screen readers distinguish between **layout tables** and **data tables**. Since email design uses `<table>`s for layout, we almost always want to specify **layout tables** for screen readers.

**Solution:**
Add `role="presentation”` to all top-level layout tables (child `<table>`s should inherit it).

[source](http://wps.pearsoned.com/wps/media/objects/8905/9119213/PG11presentationFIX.html)

**Comment by TedGoas** [comment]
Need to add role="presentation” to [all `<tables>`s](http://blog.rebelmail.com/accessibility-in-email-part-ii/).

> Add role="presentation" to each `<table>` and it will be treated like a div based layout. You only need to add it to each `<table>` element not every `<td>`

**Comment by dyspop** [comment]
This is great! 🙇
