### ISSUE TITLE
Width of some parts are not working on Windows 10 Outlook 2013

### ISSUE THREAD

**Issue by komiyaz** [emailmonday/Cerberus#72]
I tested "Hybrid" http://tedgoas.github.io/Cerberus/cerberus-hybrid.html 
using Putsmail https://putsmail.com/ to my test recipient on Outlook 2013, 
and found some blocks fails to keep their width.

![layout_cerberus20160808](https://cloud.githubusercontent.com/assets/13819576/17469977/70c6b00a-5d73-11e6-9c44-eb7c511dfc85.png)

It slightly seems that those td's with no images tend to collapse, but I am not sure.

**Comment by TedGoas** [comment]
Oof, that's no good. I'll take a look!

**Comment by TedGoas** [comment]
@komiyaz I'm having trouble reproducing.
1. What version of Windows?
2. Is the above screenshot from Litmus? Or an actual copy of Outlook 2013?
3. Are you auto-inlining CSS?

I sent myself a test email from Putsmail and this is what I see in Outlook 2013 / Windows 7:

![putsmail-ol2013-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/17482753/26d33be8-5d51-11e6-8379-abeea18f9c3e.png)

**Comment by nachonathan** [comment]
@komiyaz @TedGoas - if you're using Outlook 2013 120 DPI and use the width attribute (width="XXX"), you will need to add a matching width with inline CSS (style="width:XXX").

**Comment by TedGoas** [comment]
@nachonathan I'll be damned, that works! Thanks so much for the tip!

**Comment by TedGoas** [comment]
I don't see any other breakages in Windows Outlook, so I'll close this. If you see something that needs re-testing, please leave a comment and I'll happily re-open!
