### ISSUE TITLE
Minor difference with quotations on line #17

### ISSUE THREAD

**Issue by kmedeiros** [emailmonday/Cerberus#79]
Hi Ted, 

Line 7 in all 3 versions has different quotations wrapping the attribute than the rest of the document. Looks like the unicode ldquo; and rdquo; when I open it in Atom or VSC.

`<meta name=”x-apple-disable-message-reformatting”>`

**Comment by TedGoas** [comment]
@kmedeiros thanks, great catch!! I'll look for any other instances that might have slipped through.
