### ISSUE TITLE
Comcast renders images at 100% width and auto height

### ISSUE THREAD

**Issue by dyspop** [emailmonday/Cerberus#81]
Related to Comcast respecting the inline CSS `width:100%` but not the `max-width` nor the HTML attribute `width` and inheriting the width from the parent with an actual width (seems like `body` as no parents have actual widths specified). I'll be playing with it in litmus for a fix. Hopefully can submit a pull request for this unless the author has any good quick ideas.

**Comment by TedGoas** [comment]
@dyspop Yea I've noticed Comcast is wonky, especially in Explorer. Litmus preview show things mostly working in Comcast Firefox and Comcast Chrome, do you see that? Also, are you referring to Litmus previews? Do you have many Comcast subscribers in your mailing lists?

**Comment by dyspop** [comment]
Yes, Comcast IE. Yes, Litmus previews. I generated a public test but the page seemed like Litmus had some bugs at that time. 

Unfortunately I do have a significant amount of customers in most of the products I manage to warrant either a fix (or another framework). I really like Cerberus, I'd like to figure it out. This was in the hybrid template.

**Comment by dyspop** [comment]
I was not able to find an elegant solution. I solved it but broke the media queries for iOS iPhone native mail. If you're interested in an ugly solution I can submit a pull request but I feel it's gotten a bit out of hand for a single browser/email provider combo.

**Comment by TedGoas** [comment]
@dyspop That's awesome! ... sorta...

This is the first issue involving Comcast on Explorer I've encountered. I wouldn't want to break something elsewhere to fix an edge case like this. Though I'm super interested in seeing your fix! Is is small enough to paste the relevant code here? Or possible created/link up a Gist?

**Comment by dyspop** [comment]
I'll get you a gist

**Comment by dyspop** [comment]
Well, I thought I fixed it. It looked good in Litmus but it actually broke the fluid resizing.

**Comment by TedGoas** [comment]
@dyspop Have you looked at Litmus previews for Comcast on Explorer recently? The issue may have resolved itself.

**Comment by dyspop** [comment]
Nope, thanks. I'll look again soon.

**Comment by TedGoas** [comment]
@dyspop I just ran the hybrid template through Litmus and this included a preview of what I see for Comcast in Explorer. Some minor margin bugs towards the bottom, but nothing regarding images displaying at 100%. Do you see something similar?

![comcast-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/22187931/e364b052-e0dc-11e6-8e56-c5580684afa2.png)
