### ISSUE TITLE
Windows 10 Auto-Linking Button

### ISSUE THREAD

**Issue by longjasonm** [emailmonday/Cerberus#82]
Looks like Windows 10 is adding an underline to all links now, whether or not you want them to: [https://litmus.com/blog/windows-10-mail-email-rendering-support](https://litmus.com/blog/windows-10-mail-email-rendering-support) and it is affecting the buttons that you use: [https://cl.ly/2r1m3i2j1g2Z/Image%202016-10-19%20at%208.39.53%20PM.png](https://cl.ly/2r1m3i2j1g2Z/Image%202016-10-19%20at%208.39.53%20PM.png)

The only fix appears to be wrapping the entire content of the button (including the non-breaking space characters) in a `<span>`, giving it a unique class, and then declaring `text-decoration: none !important`.

Didn't submit a pull request because I'm not sure if or how you'd like to handle it.

**Comment by TedGoas** [comment]
@longjasonm thanks man, good catch. Seems like this should be fixed, would you agree? If you have a stable fix and want to submit a PR, that's cool (I just pushed updates, so either grab latest or hopefully they merge). Or I can test and fix this in the new few days. Have a preference?

**Comment by longjasonm** [comment]
Wondering if you should review the "Padding + Border" method for buttons
vs. the current method of just border. In this Litmus post, it looks like
it has the least number of drawbacks:
https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design

This is a fundamental change to your code so I figured it was more of a
discussion that just pull in my version and go...would you like to review
it here before we go through the PR?

**Comment by TedGoas** [comment]
@longjasonm perhaps that is worth revisiting, but it seems like a different issue from the Windows 10 underline bug reported here. What are your thoughts on your [original issue](https://github.com/TedGoas/Cerberus/issues/82#issue-184110624)?

**Comment by longjasonm** [comment]
Agreed...I will test the code for the minimum fix and submit a PR.

**Comment by TedGoas** [comment]
Fixed at PR #85
