### ISSUE TITLE
h1,h2,... tags

### ISSUE THREAD

**Issue by vincentcordel** [emailmonday/Cerberus#88]
Hey there,

Thanks for the wonderful template.

I'm wondering if using h1 (or similar) headers won't break the styling (I'm thinking Outlook green headers).

Thanks,
- Vincent

**Comment by TedGoas** [comment]
@musixite Yes, using `<h>` tags is ok, [even advisable](http://blog.rebelmail.com/accessibility-in-email-part-ii/). I've been meaning to get them into these templates!

So long as you reset default `margin`/`padding`/`line-height` and (as you say) watch out for things like [green headers](https://templates.mailchimp.com/development/css/client-specific-styles/), you should be ok!

I'd love to hear how it goes, happy testing!

**Comment by TedGoas** [comment]
@musixite Hope it goes (or went well). I'd like to close this unless you run into an issue, cool?

**Comment by vincentcordel** [comment]
Hey Ted,

Thanks for your quick reply. I tried inserting some h1,... tags and so far, so good! I haven't tested it in all email providers but I haven't received any complaints either :)

Happy holidays!
