### ISSUE TITLE
Process documentation

### ISSUE THREAD

**Issue by matdiscountmag** [emailmonday/Cerberus#9]
Don't mean to add this as an issue, as I think it is more of a question or documentation thing (sorry if I shouldn't have posted it here).  I've been researching various options for html e-mails and I like the simplicity of using Cerberus, but I'm curious about the process that should be taken.  Specifically, if I take your template without changing much, do I need to run this through a CSS inliner tool?  Or is it expected to work fine as is?

I tried running it through an inliner tool, and notice that everything between the style tags except for media queries gets removed.  I wasn't sure if this was a necessary step, or if by doing this, it would break some styles for certain email clients.

Thanks for the great work!

**Comment by skoobly** [comment]
You don't have to move the CSS inline to use this template.  It should be good as is!

**Comment by matdiscountmag** [comment]
Perfect! Thanks for the quick response.
