### ISSUE TITLE
Responsive Template Not Acting Responsively in iOS 10 Mail Client

### ISSUE THREAD

**Issue by kyletherriault** [emailmonday/Cerberus#92]
First off, just want to say I really appreciate the work you put into this, IMHO it's the best responsive template I've found. 

It appears, however, that the mail client in iOS 10 is failing to follow the media queries that forces table cells into full-width rows. Please see screenshot below. This was a paste of your sample code with no modifications.

![img_0094](https://cloud.githubusercontent.com/assets/972187/22303895/e2ce74a0-e2fa-11e6-99b5-3cab50bf49ea.PNG)

Best,
Kyle

**Comment by TedGoas** [comment]
@kyletherriault Hi Kyle, I'm having trouble reproducing this. I just ran the responsive template through every iOS device Litmus offers, as well as my own iPhone 6s running 10.2.1, and everything displays full width. Screenshot below.

**Can you give some more info?** I'm wondering if the `<style>` tag got stripped from you version, as the columns are not stacking.
* How did you sent the test email?
* Did you modify the code in any way?
* What device / OS version are you using?

![iphone7-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/22352339/aae23e1a-e3e9-11e6-849e-fffe0388eda5.png)

**Comment by kyletherriault** [comment]
Hi Ted,

- How did you sent the test email?
The test email was sent through constant contact with a custom template where you are able to replace the entire html. 
- Did you modify the code in any way?
No
- What device / OS version are you using?
iOS 10.2 (14C92)

 It rendered correctly on the Gmail App, Google Mail, and mail apps on android devices. The only one that did not render correctly was the native Mail app on iOS 10.  I viewed the original message from gmail (attached) and the <style> tags do not appear to be stripped. 

![img_0097](https://cloud.githubusercontent.com/assets/972187/22354142/a9b68050-e3e9-11e6-9599-9a80d2c8541d.PNG)
![img_0098](https://cloud.githubusercontent.com/assets/972187/22354145/ad9f0110-e3e9-11e6-838a-c61b8bfd9f61.PNG)
[original_msg.txt](https://github.com/TedGoas/Cerberus/files/733839/original_msg.txt)

**Comment by kyletherriault** [comment]
Interestingly enough, this time it's rendering the table cells into full-width rows, whereas it wasn't before. As far as I can recall, I did not modify anything to cause it to behave differently.

In both scenarios, however, I'm getting the large white-space to the right of the table which perhaps has to do with Apple's auto-scaling that I've seen others complain about.

**Comment by TedGoas** [comment]
@kyletherriault Still can't repro. Would you mind sending a test email from Constant Contact to tedgoas - at - gmail.com?

**Comment by kyletherriault** [comment]
Hi Ted,

Just sent you a test. It will come from the domain @
autoaccessoriesgarage.com

**Comment by TedGoas** [comment]
@kyletherriault Thanks, got the test. What happens when you remove the white footer at the bottom? 

![img_2500](https://cloud.githubusercontent.com/assets/1172461/22385301/17770dc4-e4a0-11e6-8ed6-30f54750f19e.PNG)

**Comment by kyletherriault** [comment]
Nice catch, didn't think of their footer because Constant Contact inserts
that outside of the custom html you're allowed to insert. Looks like they
have an explicit width set on a table cell with no class, I added the
following which seems to fix the whitespace/centering issue.

#footerContainer td {width: 100%;}
#footerContainer .HideInMobile {width: auto;}

I sent you a new test, which shows the fix, but for some reason it isn't
forcing each table cell into a line of it's own on mobile. Looks like this
is a Constant Contact issue and not your issue. Sorry to have bothered you,
but really appreciate you looking into this with me!

Best,
Kyle

**Comment by TedGoas** [comment]
Ha, yea ESP's sometimes do weird things to the final email code. Certainly no need to apologize :) glad we were able to pin point the problem. Hopefully you can get the footer you want without needing Constant Contact to add any code. Feel free to open another issue if you run into problems down the line. Cheers!

**Comment by kyletherriault** [comment]
Thanks Ted, really appreciate the help.

I'm wondering if apple mail is not able to display the table cells into
full-width rows (responsive) because the ESP is specifying an exact td
width of 610 which is greater than the max-width: of 600px in the media
query. All other clients I've tested are following the <style> declaration
and forcing the responsive design, but apple mail.

Best,
Kyle

**Comment by TedGoas** [comment]
I'm not sure. In looking at the code from the test email you sent, nothing jumps out at my as being the trouble-maker.

**Comment by raajtram** [comment]
@TedGoas - found the issue and the fix. The reason why the TD styles are not being accepted into Constant Contact is because CC strips off the `<!DOCTYPE html>` tag.

That said, the **solution** that worked for me was to **replace all the TD tags with TH**. Yeah, it's a hack but it works.

Secondly, as suggested above, the following needs to be added to fix the situation further.

```
#footerContainer th {width: 100%;}
#footerContainer .HideInMobile {width: auto;}
body > table:last-of-type table { width:100% !important; }
```
