### ISSUE TITLE
Text sizes out of proportions

### ISSUE THREAD

**Issue by ghost** [emailmonday/Cerberus#93]
First of all, awesome project! Thanks for sharing it with the world!

My problem is that in the Gmail app on Android, the text size in the mail table differs from the text size of the footer. This creates a design that's awful to watch.

It looks like this (main table is text on white bg, footer is white text on blue bg):

![screenshot_20170129-231341](https://cloud.githubusercontent.com/assets/16139664/22408426/debd97f2-e678-11e6-902f-0a32b3c622b9.png)

**Comment by TedGoas** [comment]
@BlackFayah thanks for the kind words. Judging from the screenshot above, you've modified the template quite a bit (which is great!). However, **do see the same issue if you grab a fresh copy of Cerberus and test?** I'm wondering where this issue is occurring.

**Comment by ghost** [comment]
Unfortunately, the layout goes crazy too with just a fresh copy (tested all the 3 templates) and a long url.

![screenshot_20170130-091640](https://cloud.githubusercontent.com/assets/16139664/22416262/c286d364-e6cd-11e6-9d0e-eb8b35526641.png)

**Comment by TedGoas** [comment]
@BlackFayah Hmm, that's not right. How are you sending test emails?

**Comment by ghost** [comment]
Through PHPMailer. I load the HTML template, replace certain parts (e.g. "%url%") and then send the mail.

**Comment by TedGoas** [comment]
@BlackFayah would you mind sending a test to tedgoas - at - gmail.com?

**Comment by ghost** [comment]
Done. The text is in Dutch though, so let me know if you want to know anything about the contents. P.s. the mail might have come into your Spam folder ;-)

**Comment by TedGoas** [comment]
@BlackFayah Sorry, I should have specified: can you send a test email of **the original Cerberus template** you're using to the same address? Sorry, thanks!

**Comment by ghost** [comment]
No worries, I sent it again!

**Comment by TedGoas** [comment]
@BlackFayah brilliant, thank you. Hmm, so could it be the long text link is screwing up the whole template. I tried removing it and everything snapped into place in multiple mobile Gmail clients. Have you tested that?

**Before:**
![androidgmailimap-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/22428939/e6876856-e6d6-11e6-8ccb-e2fcef8b61f3.png)

**After:**
![androidgmailimap-vertical-allowed-1366-1](https://cloud.githubusercontent.com/assets/1172461/22428952/ef90ce60-e6d6-11e6-8524-86b1c608c9e8.png)

**Comment by ghost** [comment]
Yes I have, that worked on my own version too! But I really need the link in the email because it allows people to copy + paste if they for example don't trust the button... Do you have any ideas how to fix this?

**Comment by TedGoas** [comment]
@BlackFayah I would try fiddling with `text-overflow`, `word-wrap`, `white-space`, and `overflow`, either on the `<a href>` or wrapping the link in a `<div>`. These CSS properties have [varying levels of support in email](https://www.campaignmonitor.com/css/), but there seems like enough green checkmarks in there to get a long text-string wrapping onto multiple lines in Gmail.

**Comment by ghost** [comment]
I got it to work! Font sizes are even now, which gives a nice look!

I wrapped "%url%" inside a div:

`<div style="overflow-wrap: break-word; word-wrap: break-word; -ms-word-break: break-all; word-break: break-all; text-overflow: ellipsis; white-space: normal; max-width: 300px">%url%</div>`

This gave me the following result:

Mobile:
![screenshot_20170130-225200](https://cloud.githubusercontent.com/assets/16139664/22443483/4cad487c-e73f-11e6-9f26-45e169ec4256.png)


PC:
![screen shot 2017-01-30 at 22 57 53](https://cloud.githubusercontent.com/assets/16139664/22443591/b61d3fec-e73f-11e6-8c1d-3379c81e670d.png)

**Comment by TedGoas** [comment]
@BlackFayah Great, glad you sorted it out!
