### ISSUE TITLE
Prevent Gmail From Displaying An Image Download Button

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#94]
[Using a **Sibling Selector** is an interesting idea](https://www.emailonacid.com/blog/article/email-development/prevent-gmail-from-displaying-image-download-button-in-email), worth testing.

    img.g-img + div {display:none;}

So as to not cause unintended problems.

![logo-blue-dl](https://cloud.githubusercontent.com/assets/1172461/22485341/5936d420-e7d3-11e6-9b2c-7263359fd309.png)

**Comment by longjasonm** [comment]
From what I can tell, they consistently use the class `a6S` on the `<div>` for that button.  May be able to work with that?

**Comment by TedGoas** [comment]
@longjasonm yes, I see the same in Free Gmail web as well as G Suite Basic. I will try targeting this class.

**Note:** If images are not downloaded, the entire `<style>` tag is thrown out when the "Display images below" link is clicked. So in that scenario, we won't be able to hide this download button.

![screen shot 2017-02-03 at 1 30 28 pm](https://cloud.githubusercontent.com/assets/1172461/22603395/2ee75b92-ea15-11e6-9888-fcd5fb7434a7.png)
