### ISSUE TITLE
How to actually use?

### ISSUE THREAD

**Issue by vegardsando** [emailmonday/Cerberus#95]
How do I actually use the template? I tried creating a new email message in Outlook and clicking "attach file" and browsing to the html file and choosing "attach as text". This inserts the html it seems. But the resulting email doesn't seem to be responsive. 

Am I doing it right? I can't find any info on how to actually use the template

**Comment by TedGoas** [comment]
These are meant to be used for promotional and transactional emails sent through an ESP like MailChimp, Campaign Monitor, Sales Force, etc.

I'm not quite sure how attaching code in Outlook works, but Outlook doesn't support responsive email.
