### ISSUE TITLE
Full-width Background

### ISSUE THREAD

**Issue by longjasonm** [emailmonday/Cerberus#97]
Ted,

I've adapted a version of the template that allows for "full bleed" of the background color for table rows on emails. Here is an example: 

<img width="961" alt="full-bleed-bg" src="https://cloud.githubusercontent.com/assets/1028839/22954270/7890a0c4-f2e3-11e6-90df-4ba960bae7c2.png">

Would this be something you'd be interested in integrating into the framework?

**Comment by TedGoas** [comment]
Makes sense, seems like a pretty common pattern. Mind creating a simple example? Some text and a button, maybe an image? Something that's not too large, where folks can easily replace the content but keep the background? Does that make sense?

**Comment by longjasonm** [comment]
Yep, sure does. I'll post the code snippet here first before submitting a pull request.

**Comment by pouipouidesign** [comment]
@longjasonm When do you think you'll have that snippet ready? That would be super useful to me right now ;) TIA

**Comment by TedGoas** [comment]
@longjasonm Hey man, what do you think of including this at the bottom of the template? So there is still a large, uninterrupted email wrapper for folks to use without needing to remove a full bleed section in the middle?

	<div style="max-width: 600px; margin: auto;" class="email-container">
        

        
    </div>

    

---

Good idea?

**Comment by TedGoas** [comment]
@longjasonm Hey man, I had some free time this weekend so I added a simple bit for this at the bottom of each template. Take a look and let me know if you see anything you'd improve!
