### ISSUE TITLE
Problems with supermailer

### ISSUE THREAD

**Issue by Lkzeichner22** [emailmonday/Cerberus#99]
Hey Ted,

I hope this question hasnt been asked before (I couldnt find anything with the search function) and also I have to admit that I am a HTML noob.

But I was using your template to start getting into HTML. I used it to make a newsletter for a friend. He is unsing some ancient software, that supports html. Its called supermailer. Whenever I try to send the email, it gives me an error called: 

`[style*="margin: 16px 0"] is not exisiting`

Because I had no Idea what to do, I deleted this line of code in the HTML and then it worked. Now though, the layout is messed up but only when I open it in outlook (after sending it to myself.)

Do you think you could help me out? If not I fully understand that. A big thank you to you for creating these templates.

Greetings,

lkzeichner

**Comment by TedGoas** [comment]
@Lkzeichner22 This bit of code centers email on Android 4.4. I'm not sure why supermailer hiccups when it encounters this code. **If removing this one rule allows you to use the software of your choice, I'd advise doing that.** It's a minor bug that impacts only a few email clients, certainly not a show-stopper.

Here's more information on [that Android centering issue](https://litmus.com/community/discussions/4194-why-is-email-not-centered-on-android-4-4), if you'd like to investigate alternatives.

**Comment by Lkzeichner22** [comment]
Thanks a lot! @TedGoas Have a good day!
